name: rook_sdk_apple_health
description: This package enables apps to extract and upload data from Apple Health.
version: 1.6.0
homepage: 'https://docs.tryrook.io/'
platforms:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ">=2.0.0 <3.0.0"
  protobuf: ">=3.0.0 <4.0.0"
  fixnum: "^1.0.0"
  rook_sdk_core: "^1.0.0"

#dependency_overrides:
#  rook_sdk_core:
#    path: "../rook_sdk_core"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: RookSdkAppleHealthPlugin
