// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface BloodPressureGranularDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BloodPressureGranularDataProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <code>double systolicMmHg = 2;</code>
   * @return The systolicMmHg.
   */
  double getSystolicMmHg();

  /**
   * <code>double diastolicMmHg = 3;</code>
   * @return The diastolicMmHg.
   */
  double getDiastolicMmHg();
}
