// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

/**
 * Protobuf type {@code BloodPressureObjectProto}
 */
public  final class BloodPressureObjectProto extends
    com.google.protobuf.GeneratedMessageLite<
        BloodPressureObjectProto, BloodPressureObjectProto.Builder> implements
    // @@protoc_insertion_point(message_implements:BloodPressureObjectProto)
    BloodPressureObjectProtoOrBuilder {
  private BloodPressureObjectProto() {
  }
  public static final int SYSTOLICMMHG_FIELD_NUMBER = 1;
  private double systolicMmHg_;
  /**
   * <code>double systolicMmHg = 1;</code>
   * @return The systolicMmHg.
   */
  @java.lang.Override
  public double getSystolicMmHg() {
    return systolicMmHg_;
  }
  /**
   * <code>double systolicMmHg = 1;</code>
   * @param value The systolicMmHg to set.
   */
  private void setSystolicMmHg(double value) {
    
    systolicMmHg_ = value;
  }
  /**
   * <code>double systolicMmHg = 1;</code>
   */
  private void clearSystolicMmHg() {

    systolicMmHg_ = 0D;
  }

  public static final int DIASTOLICMMHG_FIELD_NUMBER = 2;
  private double diastolicMmHg_;
  /**
   * <code>double diastolicMmHg = 2;</code>
   * @return The diastolicMmHg.
   */
  @java.lang.Override
  public double getDiastolicMmHg() {
    return diastolicMmHg_;
  }
  /**
   * <code>double diastolicMmHg = 2;</code>
   * @param value The diastolicMmHg to set.
   */
  private void setDiastolicMmHg(double value) {
    
    diastolicMmHg_ = value;
  }
  /**
   * <code>double diastolicMmHg = 2;</code>
   */
  private void clearDiastolicMmHg() {

    diastolicMmHg_ = 0D;
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code BloodPressureObjectProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:BloodPressureObjectProto)
      io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProtoOrBuilder {
    // Construct using io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>double systolicMmHg = 1;</code>
     * @return The systolicMmHg.
     */
    @java.lang.Override
    public double getSystolicMmHg() {
      return instance.getSystolicMmHg();
    }
    /**
     * <code>double systolicMmHg = 1;</code>
     * @param value The systolicMmHg to set.
     * @return This builder for chaining.
     */
    public Builder setSystolicMmHg(double value) {
      copyOnWrite();
      instance.setSystolicMmHg(value);
      return this;
    }
    /**
     * <code>double systolicMmHg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystolicMmHg() {
      copyOnWrite();
      instance.clearSystolicMmHg();
      return this;
    }

    /**
     * <code>double diastolicMmHg = 2;</code>
     * @return The diastolicMmHg.
     */
    @java.lang.Override
    public double getDiastolicMmHg() {
      return instance.getDiastolicMmHg();
    }
    /**
     * <code>double diastolicMmHg = 2;</code>
     * @param value The diastolicMmHg to set.
     * @return This builder for chaining.
     */
    public Builder setDiastolicMmHg(double value) {
      copyOnWrite();
      instance.setDiastolicMmHg(value);
      return this;
    }
    /**
     * <code>double diastolicMmHg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiastolicMmHg() {
      copyOnWrite();
      instance.clearDiastolicMmHg();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:BloodPressureObjectProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "systolicMmHg_",
            "diastolicMmHg_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto> parser = PARSER;
        if (parser == null) {
          synchronized (io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:BloodPressureObjectProto)
  private static final io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto DEFAULT_INSTANCE;
  static {
    BloodPressureObjectProto defaultInstance = new BloodPressureObjectProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BloodPressureObjectProto.class, defaultInstance);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.BloodPressureObjectProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BloodPressureObjectProto> PARSER;

  public static com.google.protobuf.Parser<BloodPressureObjectProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

