// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface ElevationGranularDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElevationGranularDataProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <code>sint32 intervalDurationSeconds = 2;</code>
   * @return The intervalDurationSeconds.
   */
  int getIntervalDurationSeconds();

  /**
   * <code>double elevationChangeMeters = 3;</code>
   * @return The elevationChangeMeters.
   */
  double getElevationChangeMeters();
}
