// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface PhysicalSummaryResultProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PhysicalSummaryResultProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.PhysicalSummaryProto synced = 1;</code>
   * @return Whether the synced field is set.
   */
  boolean hasSynced();
  /**
   * <code>.PhysicalSummaryProto synced = 1;</code>
   * @return The synced.
   */
  io.tryrook.rook_sdk_samsung_health.proto.PhysicalSummaryProto getSynced();

  /**
   * <code>bool recordsNotFound = 2;</code>
   * @return Whether the recordsNotFound field is set.
   */
  boolean hasRecordsNotFound();
  /**
   * <code>bool recordsNotFound = 2;</code>
   * @return The recordsNotFound.
   */
  boolean getRecordsNotFound();

  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   * @return The failure.
   */
  io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getFailure();

  public io.tryrook.rook_sdk_samsung_health.proto.PhysicalSummaryResultProto.ResultCase getResultCase();
}
