// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface PluginExceptionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PluginExceptionProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>sint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>sint32 code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
