// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface ResultSyncStatusWithDailyCaloriesProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultSyncStatusWithDailyCaloriesProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.SyncStatusWithDailyCaloriesProto syncStatusWithDailyCaloriesProto = 1;</code>
   * @return Whether the syncStatusWithDailyCaloriesProto field is set.
   */
  boolean hasSyncStatusWithDailyCaloriesProto();
  /**
   * <code>.SyncStatusWithDailyCaloriesProto syncStatusWithDailyCaloriesProto = 1;</code>
   * @return The syncStatusWithDailyCaloriesProto.
   */
  io.tryrook.rook_sdk_samsung_health.proto.SyncStatusWithDailyCaloriesProto getSyncStatusWithDailyCaloriesProto();

  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return Whether the pluginExceptionProto field is set.
   */
  boolean hasPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return The pluginExceptionProto.
   */
  io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getPluginExceptionProto();

  public io.tryrook.rook_sdk_samsung_health.proto.ResultSyncStatusWithDailyCaloriesProto.ResultCase getResultCase();
}
