// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

/**
 * Protobuf type {@code ResultRequestPermissionsStatusProto}
 */
public  final class ResultRequestPermissionsStatusProto extends
    com.google.protobuf.GeneratedMessageLite<
        ResultRequestPermissionsStatusProto, ResultRequestPermissionsStatusProto.Builder> implements
    // @@protoc_insertion_point(message_implements:ResultRequestPermissionsStatusProto)
    ResultRequestPermissionsStatusProtoOrBuilder {
  private ResultRequestPermissionsStatusProto() {
  }
  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase {
    REQUESTPERMISSIONSSTATUSPROTO(1),
    PLUGINEXCEPTIONPROTO(2),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return REQUESTPERMISSIONSSTATUSPROTO;
        case 2: return PLUGINEXCEPTIONPROTO;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  private void clearResult() {
    resultCase_ = 0;
    result_ = null;
  }

  public static final int REQUESTPERMISSIONSSTATUSPROTO_FIELD_NUMBER = 1;
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return Whether the requestPermissionsStatusProto field is set.
   */
  @java.lang.Override
  public boolean hasRequestPermissionsStatusProto() {
    return resultCase_ == 1;
  }
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return The enum numeric value on the wire for requestPermissionsStatusProto.
   */
  @java.lang.Override
  public int getRequestPermissionsStatusProtoValue() {
    if (resultCase_ == 1) {
      return (java.lang.Integer) result_;
    }
    return 0;
  }
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return The requestPermissionsStatusProto.
   */
  @java.lang.Override
  public io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto getRequestPermissionsStatusProto() {
    if (resultCase_ == 1) {
      io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto result = io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto.forNumber((java.lang.Integer) result_);
      return result == null ? io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto.UNRECOGNIZED : result;
    }
    return io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto.REQUEST_SENT;
  }
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @param value The enum numeric value on the wire for requestPermissionsStatusProto to set.
   */
  private void setRequestPermissionsStatusProtoValue(int value) {
    resultCase_ = 1;
    result_ = value;
  }
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @param value The requestPermissionsStatusProto to set.
   */
  private void setRequestPermissionsStatusProto(io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto value) {
    result_ = value.getNumber();
    resultCase_ = 1;
  }
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   */
  private void clearRequestPermissionsStatusProto() {
    if (resultCase_ == 1) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int PLUGINEXCEPTIONPROTO_FIELD_NUMBER = 2;
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  @java.lang.Override
  public boolean hasPluginExceptionProto() {
    return resultCase_ == 2;
  }
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  @java.lang.Override
  public io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getPluginExceptionProto() {
    if (resultCase_ == 2) {
       return (io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto) result_;
    }
    return io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  private void setPluginExceptionProto(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
    value.getClass();
  result_ = value;
    resultCase_ = 2;
  }
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  private void mergePluginExceptionProto(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
    value.getClass();
  if (resultCase_ == 2 &&
        result_ != io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.getDefaultInstance()) {
      result_ = io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.newBuilder((io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 2;
  }
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  private void clearPluginExceptionProto() {
    if (resultCase_ == 2) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ResultRequestPermissionsStatusProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:ResultRequestPermissionsStatusProto)
      io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProtoOrBuilder {
    // Construct using io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ResultCase
        getResultCase() {
      return instance.getResultCase();
    }

    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }


    /**
     * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
     * @return Whether the requestPermissionsStatusProto field is set.
     */
    @java.lang.Override
    public boolean hasRequestPermissionsStatusProto() {
      return instance.hasRequestPermissionsStatusProto();
    }
    /**
     * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
     * @return The enum numeric value on the wire for requestPermissionsStatusProto.
     */
    @java.lang.Override
    public int getRequestPermissionsStatusProtoValue() {
      return instance.getRequestPermissionsStatusProtoValue();
    }
    /**
     * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
     * @param value The enum numeric value on the wire for requestPermissionsStatusProto to set.
     * @return This builder for chaining.
     */
    public Builder setRequestPermissionsStatusProtoValue(int value) {
      copyOnWrite();
      instance.setRequestPermissionsStatusProtoValue(value);
      return this;
    }
    /**
     * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
     * @return The requestPermissionsStatusProto.
     */
    @java.lang.Override
    public io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto getRequestPermissionsStatusProto() {
      return instance.getRequestPermissionsStatusProto();
    }
    /**
     * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
     * @param value The requestPermissionsStatusProto to set.
     * @return This builder for chaining.
     */
    public Builder setRequestPermissionsStatusProto(io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto value) {
      copyOnWrite();
      instance.setRequestPermissionsStatusProto(value);
      return this;
    }
    /**
     * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestPermissionsStatusProto() {
      copyOnWrite();
      instance.clearRequestPermissionsStatusProto();
      return this;
    }

    /**
     * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
     */
    @java.lang.Override
    public boolean hasPluginExceptionProto() {
      return instance.hasPluginExceptionProto();
    }
    /**
     * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
     */
    @java.lang.Override
    public io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getPluginExceptionProto() {
      return instance.getPluginExceptionProto();
    }
    /**
     * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
     */
    public Builder setPluginExceptionProto(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
      copyOnWrite();
      instance.setPluginExceptionProto(value);
      return this;
    }
    /**
     * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
     */
    public Builder setPluginExceptionProto(
        io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.Builder builderForValue) {
      copyOnWrite();
      instance.setPluginExceptionProto(builderForValue.build());
      return this;
    }
    /**
     * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
     */
    public Builder mergePluginExceptionProto(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
      copyOnWrite();
      instance.mergePluginExceptionProto(value);
      return this;
    }
    /**
     * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
     */
    public Builder clearPluginExceptionProto() {
      copyOnWrite();
      instance.clearPluginExceptionProto();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ResultRequestPermissionsStatusProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            "resultCase_",
            io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001?\u0000\u0002<" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto> parser = PARSER;
        if (parser == null) {
          synchronized (io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ResultRequestPermissionsStatusProto)
  private static final io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto DEFAULT_INSTANCE;
  static {
    ResultRequestPermissionsStatusProto defaultInstance = new ResultRequestPermissionsStatusProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ResultRequestPermissionsStatusProto.class, defaultInstance);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ResultRequestPermissionsStatusProto> PARSER;

  public static com.google.protobuf.Parser<ResultRequestPermissionsStatusProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

