// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface ResultInt64ProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultInt64Proto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return Whether the pluginExceptionProto field is set.
   */
  boolean hasPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return The pluginExceptionProto.
   */
  io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getPluginExceptionProto();

  public io.tryrook.rook_sdk_samsung_health.proto.ResultInt64Proto.ResultCase getResultCase();
}
