// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface ResultRequestPermissionsStatusProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultRequestPermissionsStatusProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return Whether the requestPermissionsStatusProto field is set.
   */
  boolean hasRequestPermissionsStatusProto();
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return The enum numeric value on the wire for requestPermissionsStatusProto.
   */
  int getRequestPermissionsStatusProtoValue();
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return The requestPermissionsStatusProto.
   */
  io.tryrook.rook_sdk_samsung_health.proto.RequestPermissionsStatusProto getRequestPermissionsStatusProto();

  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return Whether the pluginExceptionProto field is set.
   */
  boolean hasPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return The pluginExceptionProto.
   */
  io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getPluginExceptionProto();

  public io.tryrook.rook_sdk_samsung_health.proto.ResultRequestPermissionsStatusProto.ResultCase getResultCase();
}
