// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

/**
 * Protobuf type {@code RookConfigurationProto}
 */
public  final class RookConfigurationProto extends
    com.google.protobuf.GeneratedMessageLite<
        RookConfigurationProto, RookConfigurationProto.Builder> implements
    // @@protoc_insertion_point(message_implements:RookConfigurationProto)
    RookConfigurationProtoOrBuilder {
  private RookConfigurationProto() {
    clientUUID_ = "";
    secretKey_ = "";
  }
  public static final int CLIENTUUID_FIELD_NUMBER = 1;
  private java.lang.String clientUUID_;
  /**
   * <code>string clientUUID = 1;</code>
   * @return The clientUUID.
   */
  @java.lang.Override
  public java.lang.String getClientUUID() {
    return clientUUID_;
  }
  /**
   * <code>string clientUUID = 1;</code>
   * @return The bytes for clientUUID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientUUIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientUUID_);
  }
  /**
   * <code>string clientUUID = 1;</code>
   * @param value The clientUUID to set.
   */
  private void setClientUUID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    clientUUID_ = value;
  }
  /**
   * <code>string clientUUID = 1;</code>
   */
  private void clearClientUUID() {

    clientUUID_ = getDefaultInstance().getClientUUID();
  }
  /**
   * <code>string clientUUID = 1;</code>
   * @param value The bytes for clientUUID to set.
   */
  private void setClientUUIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    clientUUID_ = value.toStringUtf8();

  }

  public static final int SECRETKEY_FIELD_NUMBER = 2;
  private java.lang.String secretKey_;
  /**
   * <code>string secretKey = 2;</code>
   * @return The secretKey.
   */
  @java.lang.Override
  public java.lang.String getSecretKey() {
    return secretKey_;
  }
  /**
   * <code>string secretKey = 2;</code>
   * @return The bytes for secretKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecretKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(secretKey_);
  }
  /**
   * <code>string secretKey = 2;</code>
   * @param value The secretKey to set.
   */
  private void setSecretKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    secretKey_ = value;
  }
  /**
   * <code>string secretKey = 2;</code>
   */
  private void clearSecretKey() {

    secretKey_ = getDefaultInstance().getSecretKey();
  }
  /**
   * <code>string secretKey = 2;</code>
   * @param value The bytes for secretKey to set.
   */
  private void setSecretKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    secretKey_ = value.toStringUtf8();

  }

  public static final int ENVIRONMENT_FIELD_NUMBER = 3;
  private int environment_;
  /**
   * <code>.RookEnvironmentProto environment = 3;</code>
   * @return The enum numeric value on the wire for environment.
   */
  @java.lang.Override
  public int getEnvironmentValue() {
    return environment_;
  }
  /**
   * <code>.RookEnvironmentProto environment = 3;</code>
   * @return The environment.
   */
  @java.lang.Override
  public io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto getEnvironment() {
    io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto result = io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto.forNumber(environment_);
    return result == null ? io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto.UNRECOGNIZED : result;
  }
  /**
   * <code>.RookEnvironmentProto environment = 3;</code>
   * @param value The enum numeric value on the wire for environment to set.
   */
  private void setEnvironmentValue(int value) {
      environment_ = value;
  }
  /**
   * <code>.RookEnvironmentProto environment = 3;</code>
   * @param value The environment to set.
   */
  private void setEnvironment(io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto value) {
    environment_ = value.getNumber();

  }
  /**
   * <code>.RookEnvironmentProto environment = 3;</code>
   */
  private void clearEnvironment() {

    environment_ = 0;
  }

  public static final int ENABLEBACKGROUNDSYNC_FIELD_NUMBER = 4;
  private boolean enableBackgroundSync_;
  /**
   * <code>bool enableBackgroundSync = 4;</code>
   * @return The enableBackgroundSync.
   */
  @java.lang.Override
  public boolean getEnableBackgroundSync() {
    return enableBackgroundSync_;
  }
  /**
   * <code>bool enableBackgroundSync = 4;</code>
   * @param value The enableBackgroundSync to set.
   */
  private void setEnableBackgroundSync(boolean value) {
    
    enableBackgroundSync_ = value;
  }
  /**
   * <code>bool enableBackgroundSync = 4;</code>
   */
  private void clearEnableBackgroundSync() {

    enableBackgroundSync_ = false;
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code RookConfigurationProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:RookConfigurationProto)
      io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProtoOrBuilder {
    // Construct using io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string clientUUID = 1;</code>
     * @return The clientUUID.
     */
    @java.lang.Override
    public java.lang.String getClientUUID() {
      return instance.getClientUUID();
    }
    /**
     * <code>string clientUUID = 1;</code>
     * @return The bytes for clientUUID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientUUIDBytes() {
      return instance.getClientUUIDBytes();
    }
    /**
     * <code>string clientUUID = 1;</code>
     * @param value The clientUUID to set.
     * @return This builder for chaining.
     */
    public Builder setClientUUID(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientUUID(value);
      return this;
    }
    /**
     * <code>string clientUUID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientUUID() {
      copyOnWrite();
      instance.clearClientUUID();
      return this;
    }
    /**
     * <code>string clientUUID = 1;</code>
     * @param value The bytes for clientUUID to set.
     * @return This builder for chaining.
     */
    public Builder setClientUUIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientUUIDBytes(value);
      return this;
    }

    /**
     * <code>string secretKey = 2;</code>
     * @return The secretKey.
     */
    @java.lang.Override
    public java.lang.String getSecretKey() {
      return instance.getSecretKey();
    }
    /**
     * <code>string secretKey = 2;</code>
     * @return The bytes for secretKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      return instance.getSecretKeyBytes();
    }
    /**
     * <code>string secretKey = 2;</code>
     * @param value The secretKey to set.
     * @return This builder for chaining.
     */
    public Builder setSecretKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setSecretKey(value);
      return this;
    }
    /**
     * <code>string secretKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecretKey() {
      copyOnWrite();
      instance.clearSecretKey();
      return this;
    }
    /**
     * <code>string secretKey = 2;</code>
     * @param value The bytes for secretKey to set.
     * @return This builder for chaining.
     */
    public Builder setSecretKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSecretKeyBytes(value);
      return this;
    }

    /**
     * <code>.RookEnvironmentProto environment = 3;</code>
     * @return The enum numeric value on the wire for environment.
     */
    @java.lang.Override
    public int getEnvironmentValue() {
      return instance.getEnvironmentValue();
    }
    /**
     * <code>.RookEnvironmentProto environment = 3;</code>
     * @param value The environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentValue(int value) {
      copyOnWrite();
      instance.setEnvironmentValue(value);
      return this;
    }
    /**
     * <code>.RookEnvironmentProto environment = 3;</code>
     * @return The environment.
     */
    @java.lang.Override
    public io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto getEnvironment() {
      return instance.getEnvironment();
    }
    /**
     * <code>.RookEnvironmentProto environment = 3;</code>
     * @param value The enum numeric value on the wire for environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironment(io.tryrook.rook_sdk_samsung_health.proto.RookEnvironmentProto value) {
      copyOnWrite();
      instance.setEnvironment(value);
      return this;
    }
    /**
     * <code>.RookEnvironmentProto environment = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironment() {
      copyOnWrite();
      instance.clearEnvironment();
      return this;
    }

    /**
     * <code>bool enableBackgroundSync = 4;</code>
     * @return The enableBackgroundSync.
     */
    @java.lang.Override
    public boolean getEnableBackgroundSync() {
      return instance.getEnableBackgroundSync();
    }
    /**
     * <code>bool enableBackgroundSync = 4;</code>
     * @param value The enableBackgroundSync to set.
     * @return This builder for chaining.
     */
    public Builder setEnableBackgroundSync(boolean value) {
      copyOnWrite();
      instance.setEnableBackgroundSync(value);
      return this;
    }
    /**
     * <code>bool enableBackgroundSync = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnableBackgroundSync() {
      copyOnWrite();
      instance.clearEnableBackgroundSync();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RookConfigurationProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "clientUUID_",
            "secretKey_",
            "environment_",
            "enableBackgroundSync_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\f\u0004\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto> parser = PARSER;
        if (parser == null) {
          synchronized (io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:RookConfigurationProto)
  private static final io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto DEFAULT_INSTANCE;
  static {
    RookConfigurationProto defaultInstance = new RookConfigurationProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RookConfigurationProto.class, defaultInstance);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.RookConfigurationProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RookConfigurationProto> PARSER;

  public static com.google.protobuf.Parser<RookConfigurationProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

