// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

/**
 * Protobuf type {@code SleepSummaryResultProto}
 */
public  final class SleepSummaryResultProto extends
    com.google.protobuf.GeneratedMessageLite<
        SleepSummaryResultProto, SleepSummaryResultProto.Builder> implements
    // @@protoc_insertion_point(message_implements:SleepSummaryResultProto)
    SleepSummaryResultProtoOrBuilder {
  private SleepSummaryResultProto() {
  }
  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase {
    SYNCED(1),
    RECORDSNOTFOUND(2),
    FAILURE(3),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return SYNCED;
        case 2: return RECORDSNOTFOUND;
        case 3: return FAILURE;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  private void clearResult() {
    resultCase_ = 0;
    result_ = null;
  }

  public static final int SYNCED_FIELD_NUMBER = 1;
  /**
   * <code>.SleepSummariesProto synced = 1;</code>
   */
  @java.lang.Override
  public boolean hasSynced() {
    return resultCase_ == 1;
  }
  /**
   * <code>.SleepSummariesProto synced = 1;</code>
   */
  @java.lang.Override
  public io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto getSynced() {
    if (resultCase_ == 1) {
       return (io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto) result_;
    }
    return io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto.getDefaultInstance();
  }
  /**
   * <code>.SleepSummariesProto synced = 1;</code>
   */
  private void setSynced(io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto value) {
    value.getClass();
  result_ = value;
    resultCase_ = 1;
  }
  /**
   * <code>.SleepSummariesProto synced = 1;</code>
   */
  private void mergeSynced(io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto value) {
    value.getClass();
  if (resultCase_ == 1 &&
        result_ != io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto.getDefaultInstance()) {
      result_ = io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto.newBuilder((io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 1;
  }
  /**
   * <code>.SleepSummariesProto synced = 1;</code>
   */
  private void clearSynced() {
    if (resultCase_ == 1) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int RECORDSNOTFOUND_FIELD_NUMBER = 2;
  /**
   * <code>bool recordsNotFound = 2;</code>
   * @return Whether the recordsNotFound field is set.
   */
  @java.lang.Override
  public boolean hasRecordsNotFound() {
    return resultCase_ == 2;
  }
  /**
   * <code>bool recordsNotFound = 2;</code>
   * @return The recordsNotFound.
   */
  @java.lang.Override
  public boolean getRecordsNotFound() {
    if (resultCase_ == 2) {
      return (java.lang.Boolean) result_;
    }
    return false;
  }
  /**
   * <code>bool recordsNotFound = 2;</code>
   * @param value The recordsNotFound to set.
   */
  private void setRecordsNotFound(boolean value) {
    resultCase_ = 2;
    result_ = value;
  }
  /**
   * <code>bool recordsNotFound = 2;</code>
   */
  private void clearRecordsNotFound() {
    if (resultCase_ == 2) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int FAILURE_FIELD_NUMBER = 3;
  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   */
  @java.lang.Override
  public boolean hasFailure() {
    return resultCase_ == 3;
  }
  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   */
  @java.lang.Override
  public io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getFailure() {
    if (resultCase_ == 3) {
       return (io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto) result_;
    }
    return io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   */
  private void setFailure(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
    value.getClass();
  result_ = value;
    resultCase_ = 3;
  }
  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   */
  private void mergeFailure(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
    value.getClass();
  if (resultCase_ == 3 &&
        result_ != io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.getDefaultInstance()) {
      result_ = io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.newBuilder((io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 3;
  }
  /**
   * <code>.PluginExceptionProto failure = 3;</code>
   */
  private void clearFailure() {
    if (resultCase_ == 3) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code SleepSummaryResultProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:SleepSummaryResultProto)
      io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProtoOrBuilder {
    // Construct using io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ResultCase
        getResultCase() {
      return instance.getResultCase();
    }

    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }


    /**
     * <code>.SleepSummariesProto synced = 1;</code>
     */
    @java.lang.Override
    public boolean hasSynced() {
      return instance.hasSynced();
    }
    /**
     * <code>.SleepSummariesProto synced = 1;</code>
     */
    @java.lang.Override
    public io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto getSynced() {
      return instance.getSynced();
    }
    /**
     * <code>.SleepSummariesProto synced = 1;</code>
     */
    public Builder setSynced(io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto value) {
      copyOnWrite();
      instance.setSynced(value);
      return this;
    }
    /**
     * <code>.SleepSummariesProto synced = 1;</code>
     */
    public Builder setSynced(
        io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSynced(builderForValue.build());
      return this;
    }
    /**
     * <code>.SleepSummariesProto synced = 1;</code>
     */
    public Builder mergeSynced(io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto value) {
      copyOnWrite();
      instance.mergeSynced(value);
      return this;
    }
    /**
     * <code>.SleepSummariesProto synced = 1;</code>
     */
    public Builder clearSynced() {
      copyOnWrite();
      instance.clearSynced();
      return this;
    }

    /**
     * <code>bool recordsNotFound = 2;</code>
     * @return Whether the recordsNotFound field is set.
     */
    @java.lang.Override
    public boolean hasRecordsNotFound() {
      return instance.hasRecordsNotFound();
    }
    /**
     * <code>bool recordsNotFound = 2;</code>
     * @return The recordsNotFound.
     */
    @java.lang.Override
    public boolean getRecordsNotFound() {
      return instance.getRecordsNotFound();
    }
    /**
     * <code>bool recordsNotFound = 2;</code>
     * @param value The recordsNotFound to set.
     * @return This builder for chaining.
     */
    public Builder setRecordsNotFound(boolean value) {
      copyOnWrite();
      instance.setRecordsNotFound(value);
      return this;
    }
    /**
     * <code>bool recordsNotFound = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordsNotFound() {
      copyOnWrite();
      instance.clearRecordsNotFound();
      return this;
    }

    /**
     * <code>.PluginExceptionProto failure = 3;</code>
     */
    @java.lang.Override
    public boolean hasFailure() {
      return instance.hasFailure();
    }
    /**
     * <code>.PluginExceptionProto failure = 3;</code>
     */
    @java.lang.Override
    public io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getFailure() {
      return instance.getFailure();
    }
    /**
     * <code>.PluginExceptionProto failure = 3;</code>
     */
    public Builder setFailure(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
      copyOnWrite();
      instance.setFailure(value);
      return this;
    }
    /**
     * <code>.PluginExceptionProto failure = 3;</code>
     */
    public Builder setFailure(
        io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.Builder builderForValue) {
      copyOnWrite();
      instance.setFailure(builderForValue.build());
      return this;
    }
    /**
     * <code>.PluginExceptionProto failure = 3;</code>
     */
    public Builder mergeFailure(io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto value) {
      copyOnWrite();
      instance.mergeFailure(value);
      return this;
    }
    /**
     * <code>.PluginExceptionProto failure = 3;</code>
     */
    public Builder clearFailure() {
      copyOnWrite();
      instance.clearFailure();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SleepSummaryResultProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            "resultCase_",
            io.tryrook.rook_sdk_samsung_health.proto.SleepSummariesProto.class,
            io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001<\u0000\u0002:" +
              "\u0000\u0003<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto> parser = PARSER;
        if (parser == null) {
          synchronized (io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:SleepSummaryResultProto)
  private static final io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto DEFAULT_INSTANCE;
  static {
    SleepSummaryResultProto defaultInstance = new SleepSummaryResultProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SleepSummaryResultProto.class, defaultInstance);
  }

  public static io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryResultProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SleepSummaryResultProto> PARSER;

  public static com.google.protobuf.Parser<SleepSummaryResultProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

