// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package io.tryrook.rook_sdk_samsung_health.proto;

public interface SyncStatusWithIntResultProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SyncStatusWithIntResultProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.SyncStatusWithIntProto success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.SyncStatusWithIntProto success = 1;</code>
   * @return The success.
   */
  io.tryrook.rook_sdk_samsung_health.proto.SyncStatusWithIntProto getSuccess();

  /**
   * <code>.PluginExceptionProto failure = 2;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>.PluginExceptionProto failure = 2;</code>
   * @return The failure.
   */
  io.tryrook.rook_sdk_samsung_health.proto.PluginExceptionProto getFailure();

  public io.tryrook.rook_sdk_samsung_health.proto.SyncStatusWithIntResultProto.ResultCase getResultCase();
}
