import 'package:rook_sdk_apple_health/src/platform/rook_sdk_apple_health_platform_interface.dart';
import 'package:rook_sdk_core/rook_sdk_core.dart';

class AHRookContinuousUpload {
  AHRookContinuousUpload._();

  /// Checks if the continuous upload of summaries and events is enabled.
  static Future<bool> isContinuousUploadEnabled() {
    return RookSdkAppleHealthPlatform.instance.isContinuousUploadEnabled();
  }

  /// Enables the continuous upload of summaries and events.
  /// Every time the user opens the app it will try to upload the summaries,
  /// before use this method is necessary to add a user id and request permissions.
  ///
  /// * [enableLogs] See the logs generated by this SDK.
  /// * [clientUUID] Client unique identifier provided by ROOK.
  /// * [secretKey] Client secretKey provided by ROOK.
  /// * [environment] Behaviour configuration.
  static Future<void> enableContinuousUpload({
    required bool enableNativeLogs,
    required String clientUUID,
    required String secretKey,
    required RookEnvironment environment,
  }) {
    return RookSdkAppleHealthPlatform.instance.enableContinuousUpload(
      enableNativeLogs,
      clientUUID,
      secretKey,
      environment,
    );
  }

  /// Disables the continuous upload of summaries and events.
  static Future<void> disableContinuousUpload() {
    return RookSdkAppleHealthPlatform.instance.disableContinuousUpload();
  }
}
