import 'package:rook_sdk_apple_health/src/platform/rook_sdk_apple_health_platform_interface.dart';

/// This class allows you to schedule an periodic background health data syncs.
class AHRookBackgroundSync {
  AHRookBackgroundSync._();

  /// Checks if background sync is already scheduled.
  static Future<bool> isScheduled() {
    return RookSdkAppleHealthPlatform.instance.isScheduled();
  }

  /// Enables the background upload of summaries and events,
  /// before use this method is necessary to add a user id and request permissions.
  ///
  /// * [enableNativeLogs] See the logs generated by this SDK.
  static Future<void> enableBackground({required bool enableNativeLogs}) {
    return RookSdkAppleHealthPlatform.instance.schedule(enableNativeLogs);
  }

  /// Disables the background upload of summaries and events.
  static Future<void> disableBackground() {
    return RookSdkAppleHealthPlatform.instance.cancel();
  }
}
