import 'package:rook_sdk_apple_health/src/platform/rook_sdk_apple_health_platform_interface.dart';
import 'package:rook_sdk_core/rook_sdk_core.dart';

/// This class allows you to schedule an periodic background health data syncs.
class AHRookBackgroundSync {
  AHRookBackgroundSync._();

  /// Enables the background upload of summaries and events,
  /// before use this method is necessary to add a user id and request permissions.
  ///
  /// * [enableLogs] See the logs generated by this SDK.
  /// * [clientUUID] Client unique identifier provided by ROOK.
  /// * [secretKey] Client secretKey provided by ROOK.
  /// * [environment] Behaviour configuration.
  static Future<void> enableBackground({
    required bool enableNativeLogs,
    required String clientUUID,
    required String secretKey,
    required RookEnvironment environment,
  }) {
    return RookSdkAppleHealthPlatform.instance.enableBackground(
      enableNativeLogs,
      clientUUID,
      secretKey,
      environment,
    );
  }

  /// Disables the background upload of summaries and events.
  static Future<void> disableBackground() {
    return RookSdkAppleHealthPlatform.instance.disableBackground();
  }
}
