import 'package:rook_sdk_apple_health/src/platform/rook_sdk_apple_health_platform_interface.dart';

/// Helper class to launch 29 days historic health data synchronizations.
class AHRookContinuousUpload {
  AHRookContinuousUpload._();

  /// Checks if the continuous upload of summaries and events is enabled.
  static Future<bool> isContinuousUploadEnabled() {
    return RookSdkAppleHealthPlatform.instance.isContinuousUploadEnabled();
  }

  /// Enables the continuous upload of summaries and events.
  /// Every time the user opens the app it will try to upload the summaries,
  /// before use this method is necessary to add a user id and request permissions.
  ///
  /// * [enableNativeLogs] See the logs generated by this SDK.
  static Future<void> enableContinuousUpload({required bool enableNativeLogs}) {
    return RookSdkAppleHealthPlatform.instance.enableContinuousUpload(
      enableNativeLogs,
    );
  }

  /// Disables the continuous upload of summaries and events.
  static Future<void> disableContinuousUpload() {
    return RookSdkAppleHealthPlatform.instance.disableContinuousUpload();
  }
}
