package io.tryrook.rook_sdk_samsung_health.mapper

import io.tryrook.rook_sdk_samsung_health.DEFAULT_DOUBLE
import io.tryrook.rook_sdk_samsung_health.DEFAULT_INT
import io.tryrook.rook_sdk_samsung_health.extension.toProtoString
import io.tryrook.rook_sdk_samsung_health.proto.SleepSummaryProto
import io.tryrook.sdk.samsung.domain.model.SHSleepSummary

fun SHSleepSummary.toProto(): SleepSummaryProto {
    return SleepSummaryProto.newBuilder()
        .setDateTime(dateTime.toProtoString())
        .setSourceOfData(sourceOfData)
        .setWasTheUserUnderPhysicalActivity(wasTheUserUnderPhysicalActivity)
        .setSleepStartDateTime(sleepStartDateTime.toProtoString())
        .setSleepEndDateTime(sleepEndDateTime.toProtoString())
        .setSleepDate(sleepDate.toProtoString())
        .setSleepDurationSeconds(sleepDurationSeconds ?: DEFAULT_INT)
        .setTimeInBedSeconds(timeInBedSeconds ?: DEFAULT_INT)
        .setLightSleepDurationSeconds(lightSleepDurationSeconds ?: DEFAULT_INT)
        .setRemSleepDurationSeconds(remSleepDurationSeconds ?: DEFAULT_INT)
        .setDeepSleepDurationSeconds(deepSleepDurationSeconds ?: DEFAULT_INT)
        .setTimeToFallAsleepSeconds(timeToFallAsleepSeconds ?: DEFAULT_INT)
        .setTimeAwakeDuringSleepSeconds(timeAwakeDuringSleepSeconds ?: DEFAULT_INT)
        .setSleepQualityRating1To5Score(sleepQualityRating1To5Score ?: DEFAULT_INT)
        .setSleepEfficiency1To100Score(sleepEfficiency1To100Score ?: DEFAULT_INT)
        .setSleepGoalSeconds(sleepGoalSeconds ?: DEFAULT_INT)
        .setSleepContinuity1To5Score(sleepContinuity1To5Score ?: DEFAULT_INT)
        .setSleepContinuity1To5Rating(sleepContinuity1To5Rating ?: DEFAULT_INT)
        .setHrMaximumBpm(hrMaximumBpm ?: DEFAULT_INT)
        .setHrMinimumBpm(hrMinimumBpm ?: DEFAULT_INT)
        .setHrAvgBpm(hrAvgBpm ?: DEFAULT_INT)
        .setHrRestingBpm(hrRestingBpm ?: DEFAULT_INT)
        .setHrBasalBpm(hrBasalBpm ?: DEFAULT_INT)
        .addAllHrGranularData(hrGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .setHrvAvgRmssd(hrvAvgRmssd ?: DEFAULT_DOUBLE)
        .setHrvAvgSdnn(hrvAvgSdnn ?: DEFAULT_DOUBLE)
        .addAllHrvSdnnGranularData(hrvSdnnGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .addAllHrvRmssdGranularData(hrvRmssdGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .addAllTemperatureMinimum(temperatureMinimum?.toObjectProto()?.let { listOf(it) } ?: emptyList())
        .addAllTemperatureAvg(temperatureAvg?.toObjectProto()?.let { listOf(it) } ?: emptyList())
        .addAllTemperatureMaximum(temperatureMaximum?.toObjectProto()?.let { listOf(it) } ?: emptyList())
        .addAllTemperatureGranularData(temperatureGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .addAllTemperatureDelta(temperatureDelta?.toObjectProto()?.let { listOf(it) } ?: emptyList())
        .setBreathsMinimumPerMin(breathsMinimumPerMin ?: DEFAULT_DOUBLE)
        .setBreathsAvgPerMin(breathsAvgPerMin ?: DEFAULT_DOUBLE)
        .setBreathsMaximumPerMin(breathsMaximumPerMin ?: DEFAULT_DOUBLE)
        .addAllBreathingGranularData(breathingGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .setSnoringEventsCount(snoringEventsCount ?: DEFAULT_INT)
        .setSnoringDurationTotalSeconds(snoringDurationTotalSeconds ?: DEFAULT_INT)
        .addAllSnoringGranularData(snoringGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .setSaturationAvgPercentage(saturationAvgPercentage ?: DEFAULT_DOUBLE)
        .setSaturationMinimumPercentage(saturationMinimumPercentage ?: DEFAULT_DOUBLE)
        .setSaturationMaximumPercentage(saturationMaximumPercentage ?: DEFAULT_DOUBLE)
        .addAllSaturationGranularData(saturationGranularData?.map { it.toGranularDataProto() } ?: emptyList())
        .build()
}
