// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface ActivityEventsProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActivityEventsProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .ActivityEventProto elements = 1;</code>
   */
  java.util.List<com.rookmotion.rook_sdk_health_connect.proto.ActivityEventProto> 
      getElementsList();
  /**
   * <code>repeated .ActivityEventProto elements = 1;</code>
   */
  com.rookmotion.rook_sdk_health_connect.proto.ActivityEventProto getElements(int index);
  /**
   * <code>repeated .ActivityEventProto elements = 1;</code>
   */
  int getElementsCount();
}
