// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface AndroidPermissionsSummaryProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AndroidPermissionsSummaryProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool permissionsGranted = 1;</code>
   * @return The permissionsGranted.
   */
  boolean getPermissionsGranted();

  /**
   * <code>bool dialogDisplayed = 2;</code>
   * @return The dialogDisplayed.
   */
  boolean getDialogDisplayed();
}
