// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface AuthorizedDataSourceV2ListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizedDataSourceV2ListProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .AuthorizedDataSourceV2Proto list = 1;</code>
   */
  java.util.List<com.rookmotion.rook_sdk_health_connect.proto.AuthorizedDataSourceV2Proto> 
      getListList();
  /**
   * <code>repeated .AuthorizedDataSourceV2Proto list = 1;</code>
   */
  com.rookmotion.rook_sdk_health_connect.proto.AuthorizedDataSourceV2Proto getList(int index);
  /**
   * <code>repeated .AuthorizedDataSourceV2Proto list = 1;</code>
   */
  int getListCount();
}
