// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface AuthorizedDataSourceV2ResultProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizedDataSourceV2ResultProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.AuthorizedDataSourceV2ListProto success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.AuthorizedDataSourceV2ListProto success = 1;</code>
   * @return The success.
   */
  com.rookmotion.rook_sdk_health_connect.proto.AuthorizedDataSourceV2ListProto getSuccess();

  /**
   * <code>.PluginExceptionProto failure = 2;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>.PluginExceptionProto failure = 2;</code>
   * @return The failure.
   */
  com.rookmotion.rook_sdk_health_connect.proto.PluginExceptionProto getFailure();

  public com.rookmotion.rook_sdk_health_connect.proto.AuthorizedDataSourceV2ResultProto.ResultCase getResultCase();
}
