// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface BloodPressureObjectProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BloodPressureObjectProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double systolicMmHg = 1;</code>
   * @return The systolicMmHg.
   */
  double getSystolicMmHg();

  /**
   * <code>double diastolicMmHg = 2;</code>
   * @return The diastolicMmHg.
   */
  double getDiastolicMmHg();
}
