// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface BodySummaryResultProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BodySummaryResultProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.BodySummaryProto success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.BodySummaryProto success = 1;</code>
   * @return The success.
   */
  com.rookmotion.rook_sdk_health_connect.proto.BodySummaryProto getSuccess();

  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   * @return The failure.
   */
  com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto getFailure();

  public com.rookmotion.rook_sdk_health_connect.proto.BodySummaryResultProto.ResultCase getResultCase();
}
