// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface CaloriesProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CaloriesProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double basal = 1;</code>
   * @return The basal.
   */
  double getBasal();

  /**
   * <code>double active = 2;</code>
   * @return The active.
   */
  double getActive();
}
