// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface DataSourcesProtoListWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataSourcesProtoListWrapper)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .DataSourceProto dataSources = 1;</code>
   */
  java.util.List<com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto> 
      getDataSourcesList();
  /**
   * <code>repeated .DataSourceProto dataSources = 1;</code>
   */
  com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto getDataSources(int index);
  /**
   * <code>repeated .DataSourceProto dataSources = 1;</code>
   */
  int getDataSourcesCount();
}
