// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

/**
 * Protobuf type {@code DataSourceProto}
 */
public  final class DataSourceProto extends
    com.google.protobuf.GeneratedMessageLite<
        DataSourceProto, DataSourceProto.Builder> implements
    // @@protoc_insertion_point(message_implements:DataSourceProto)
    DataSourceProtoOrBuilder {
  private DataSourceProto() {
    name_ = "";
    description_ = "";
    image_ = "";
    authorizationUrl_ = "";
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private java.lang.String description_;
  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 2;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 2;</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 2;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static final int IMAGE_FIELD_NUMBER = 3;
  private java.lang.String image_;
  /**
   * <code>string image = 3;</code>
   * @return The image.
   */
  @java.lang.Override
  public java.lang.String getImage() {
    return image_;
  }
  /**
   * <code>string image = 3;</code>
   * @return The bytes for image.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(image_);
  }
  /**
   * <code>string image = 3;</code>
   * @param value The image to set.
   */
  private void setImage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    image_ = value;
  }
  /**
   * <code>string image = 3;</code>
   */
  private void clearImage() {

    image_ = getDefaultInstance().getImage();
  }
  /**
   * <code>string image = 3;</code>
   * @param value The bytes for image to set.
   */
  private void setImageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    image_ = value.toStringUtf8();

  }

  public static final int CONNECTED_FIELD_NUMBER = 4;
  private boolean connected_;
  /**
   * <code>bool connected = 4;</code>
   * @return The connected.
   */
  @java.lang.Override
  public boolean getConnected() {
    return connected_;
  }
  /**
   * <code>bool connected = 4;</code>
   * @param value The connected to set.
   */
  private void setConnected(boolean value) {
    
    connected_ = value;
  }
  /**
   * <code>bool connected = 4;</code>
   */
  private void clearConnected() {

    connected_ = false;
  }

  public static final int AUTHORIZATIONURL_FIELD_NUMBER = 5;
  private java.lang.String authorizationUrl_;
  /**
   * <code>string authorizationUrl = 5;</code>
   * @return The authorizationUrl.
   */
  @java.lang.Override
  public java.lang.String getAuthorizationUrl() {
    return authorizationUrl_;
  }
  /**
   * <code>string authorizationUrl = 5;</code>
   * @return The bytes for authorizationUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorizationUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(authorizationUrl_);
  }
  /**
   * <code>string authorizationUrl = 5;</code>
   * @param value The authorizationUrl to set.
   */
  private void setAuthorizationUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    authorizationUrl_ = value;
  }
  /**
   * <code>string authorizationUrl = 5;</code>
   */
  private void clearAuthorizationUrl() {

    authorizationUrl_ = getDefaultInstance().getAuthorizationUrl();
  }
  /**
   * <code>string authorizationUrl = 5;</code>
   * @param value The bytes for authorizationUrl to set.
   */
  private void setAuthorizationUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    authorizationUrl_ = value.toStringUtf8();

  }

  public static final int AUTHORIZATIONURLISNULL_FIELD_NUMBER = 6;
  private boolean authorizationUrlIsNull_;
  /**
   * <code>bool authorizationUrlIsNull = 6;</code>
   * @return The authorizationUrlIsNull.
   */
  @java.lang.Override
  public boolean getAuthorizationUrlIsNull() {
    return authorizationUrlIsNull_;
  }
  /**
   * <code>bool authorizationUrlIsNull = 6;</code>
   * @param value The authorizationUrlIsNull to set.
   */
  private void setAuthorizationUrlIsNull(boolean value) {
    
    authorizationUrlIsNull_ = value;
  }
  /**
   * <code>bool authorizationUrlIsNull = 6;</code>
   */
  private void clearAuthorizationUrlIsNull() {

    authorizationUrlIsNull_ = false;
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code DataSourceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:DataSourceProto)
      com.rookmotion.rook_sdk_health_connect.proto.DataSourceProtoOrBuilder {
    // Construct using com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>string image = 3;</code>
     * @return The image.
     */
    @java.lang.Override
    public java.lang.String getImage() {
      return instance.getImage();
    }
    /**
     * <code>string image = 3;</code>
     * @return The bytes for image.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageBytes() {
      return instance.getImageBytes();
    }
    /**
     * <code>string image = 3;</code>
     * @param value The image to set.
     * @return This builder for chaining.
     */
    public Builder setImage(
        java.lang.String value) {
      copyOnWrite();
      instance.setImage(value);
      return this;
    }
    /**
     * <code>string image = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImage() {
      copyOnWrite();
      instance.clearImage();
      return this;
    }
    /**
     * <code>string image = 3;</code>
     * @param value The bytes for image to set.
     * @return This builder for chaining.
     */
    public Builder setImageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImageBytes(value);
      return this;
    }

    /**
     * <code>bool connected = 4;</code>
     * @return The connected.
     */
    @java.lang.Override
    public boolean getConnected() {
      return instance.getConnected();
    }
    /**
     * <code>bool connected = 4;</code>
     * @param value The connected to set.
     * @return This builder for chaining.
     */
    public Builder setConnected(boolean value) {
      copyOnWrite();
      instance.setConnected(value);
      return this;
    }
    /**
     * <code>bool connected = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnected() {
      copyOnWrite();
      instance.clearConnected();
      return this;
    }

    /**
     * <code>string authorizationUrl = 5;</code>
     * @return The authorizationUrl.
     */
    @java.lang.Override
    public java.lang.String getAuthorizationUrl() {
      return instance.getAuthorizationUrl();
    }
    /**
     * <code>string authorizationUrl = 5;</code>
     * @return The bytes for authorizationUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorizationUrlBytes() {
      return instance.getAuthorizationUrlBytes();
    }
    /**
     * <code>string authorizationUrl = 5;</code>
     * @param value The authorizationUrl to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorizationUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setAuthorizationUrl(value);
      return this;
    }
    /**
     * <code>string authorizationUrl = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorizationUrl() {
      copyOnWrite();
      instance.clearAuthorizationUrl();
      return this;
    }
    /**
     * <code>string authorizationUrl = 5;</code>
     * @param value The bytes for authorizationUrl to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorizationUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAuthorizationUrlBytes(value);
      return this;
    }

    /**
     * <code>bool authorizationUrlIsNull = 6;</code>
     * @return The authorizationUrlIsNull.
     */
    @java.lang.Override
    public boolean getAuthorizationUrlIsNull() {
      return instance.getAuthorizationUrlIsNull();
    }
    /**
     * <code>bool authorizationUrlIsNull = 6;</code>
     * @param value The authorizationUrlIsNull to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorizationUrlIsNull(boolean value) {
      copyOnWrite();
      instance.setAuthorizationUrlIsNull(value);
      return this;
    }
    /**
     * <code>bool authorizationUrlIsNull = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorizationUrlIsNull() {
      copyOnWrite();
      instance.clearAuthorizationUrlIsNull();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:DataSourceProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "description_",
            "image_",
            "connected_",
            "authorizationUrl_",
            "authorizationUrlIsNull_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0007\u0005\u0208\u0006\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto> parser = PARSER;
        if (parser == null) {
          synchronized (com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:DataSourceProto)
  private static final com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto DEFAULT_INSTANCE;
  static {
    DataSourceProto defaultInstance = new DataSourceProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DataSourceProto.class, defaultInstance);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.DataSourceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DataSourceProto> PARSER;

  public static com.google.protobuf.Parser<DataSourceProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

