// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface DiagnosticSyncStateProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DiagnosticSyncStateProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool enabled = 1;</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>string lastSync = 2;</code>
   * @return The lastSync.
   */
  java.lang.String getLastSync();
  /**
   * <code>string lastSync = 2;</code>
   * @return The bytes for lastSync.
   */
  com.google.protobuf.ByteString
      getLastSyncBytes();
}
