// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

/**
 * Protobuf type {@code ElevationGranularDataProto}
 */
public  final class ElevationGranularDataProto extends
    com.google.protobuf.GeneratedMessageLite<
        ElevationGranularDataProto, ElevationGranularDataProto.Builder> implements
    // @@protoc_insertion_point(message_implements:ElevationGranularDataProto)
    ElevationGranularDataProtoOrBuilder {
  private ElevationGranularDataProto() {
    dateTime_ = "";
  }
  public static final int DATETIME_FIELD_NUMBER = 1;
  private java.lang.String dateTime_;
  /**
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  @java.lang.Override
  public java.lang.String getDateTime() {
    return dateTime_;
  }
  /**
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateTimeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dateTime_);
  }
  /**
   * <code>string dateTime = 1;</code>
   * @param value The dateTime to set.
   */
  private void setDateTime(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    dateTime_ = value;
  }
  /**
   * <code>string dateTime = 1;</code>
   */
  private void clearDateTime() {

    dateTime_ = getDefaultInstance().getDateTime();
  }
  /**
   * <code>string dateTime = 1;</code>
   * @param value The bytes for dateTime to set.
   */
  private void setDateTimeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    dateTime_ = value.toStringUtf8();

  }

  public static final int INTERVALDURATIONSECONDS_FIELD_NUMBER = 2;
  private int intervalDurationSeconds_;
  /**
   * <code>sint32 intervalDurationSeconds = 2;</code>
   * @return The intervalDurationSeconds.
   */
  @java.lang.Override
  public int getIntervalDurationSeconds() {
    return intervalDurationSeconds_;
  }
  /**
   * <code>sint32 intervalDurationSeconds = 2;</code>
   * @param value The intervalDurationSeconds to set.
   */
  private void setIntervalDurationSeconds(int value) {
    
    intervalDurationSeconds_ = value;
  }
  /**
   * <code>sint32 intervalDurationSeconds = 2;</code>
   */
  private void clearIntervalDurationSeconds() {

    intervalDurationSeconds_ = 0;
  }

  public static final int ELEVATIONCHANGEMETERS_FIELD_NUMBER = 3;
  private double elevationChangeMeters_;
  /**
   * <code>double elevationChangeMeters = 3;</code>
   * @return The elevationChangeMeters.
   */
  @java.lang.Override
  public double getElevationChangeMeters() {
    return elevationChangeMeters_;
  }
  /**
   * <code>double elevationChangeMeters = 3;</code>
   * @param value The elevationChangeMeters to set.
   */
  private void setElevationChangeMeters(double value) {
    
    elevationChangeMeters_ = value;
  }
  /**
   * <code>double elevationChangeMeters = 3;</code>
   */
  private void clearElevationChangeMeters() {

    elevationChangeMeters_ = 0D;
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ElevationGranularDataProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:ElevationGranularDataProto)
      com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProtoOrBuilder {
    // Construct using com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string dateTime = 1;</code>
     * @return The dateTime.
     */
    @java.lang.Override
    public java.lang.String getDateTime() {
      return instance.getDateTime();
    }
    /**
     * <code>string dateTime = 1;</code>
     * @return The bytes for dateTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateTimeBytes() {
      return instance.getDateTimeBytes();
    }
    /**
     * <code>string dateTime = 1;</code>
     * @param value The dateTime to set.
     * @return This builder for chaining.
     */
    public Builder setDateTime(
        java.lang.String value) {
      copyOnWrite();
      instance.setDateTime(value);
      return this;
    }
    /**
     * <code>string dateTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateTime() {
      copyOnWrite();
      instance.clearDateTime();
      return this;
    }
    /**
     * <code>string dateTime = 1;</code>
     * @param value The bytes for dateTime to set.
     * @return This builder for chaining.
     */
    public Builder setDateTimeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDateTimeBytes(value);
      return this;
    }

    /**
     * <code>sint32 intervalDurationSeconds = 2;</code>
     * @return The intervalDurationSeconds.
     */
    @java.lang.Override
    public int getIntervalDurationSeconds() {
      return instance.getIntervalDurationSeconds();
    }
    /**
     * <code>sint32 intervalDurationSeconds = 2;</code>
     * @param value The intervalDurationSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setIntervalDurationSeconds(int value) {
      copyOnWrite();
      instance.setIntervalDurationSeconds(value);
      return this;
    }
    /**
     * <code>sint32 intervalDurationSeconds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntervalDurationSeconds() {
      copyOnWrite();
      instance.clearIntervalDurationSeconds();
      return this;
    }

    /**
     * <code>double elevationChangeMeters = 3;</code>
     * @return The elevationChangeMeters.
     */
    @java.lang.Override
    public double getElevationChangeMeters() {
      return instance.getElevationChangeMeters();
    }
    /**
     * <code>double elevationChangeMeters = 3;</code>
     * @param value The elevationChangeMeters to set.
     * @return This builder for chaining.
     */
    public Builder setElevationChangeMeters(double value) {
      copyOnWrite();
      instance.setElevationChangeMeters(value);
      return this;
    }
    /**
     * <code>double elevationChangeMeters = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearElevationChangeMeters() {
      copyOnWrite();
      instance.clearElevationChangeMeters();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ElevationGranularDataProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "dateTime_",
            "intervalDurationSeconds_",
            "elevationChangeMeters_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u000f" +
              "\u0003\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto> parser = PARSER;
        if (parser == null) {
          synchronized (com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ElevationGranularDataProto)
  private static final com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto DEFAULT_INSTANCE;
  static {
    ElevationGranularDataProto defaultInstance = new ElevationGranularDataProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ElevationGranularDataProto.class, defaultInstance);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.ElevationGranularDataProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ElevationGranularDataProto> PARSER;

  public static com.google.protobuf.Parser<ElevationGranularDataProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

