// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

/**
 * Protobuf type {@code HearRateResultProto}
 */
public  final class HearRateResultProto extends
    com.google.protobuf.GeneratedMessageLite<
        HearRateResultProto, HearRateResultProto.Builder> implements
    // @@protoc_insertion_point(message_implements:HearRateResultProto)
    HearRateResultProtoOrBuilder {
  private HearRateResultProto() {
  }
  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase {
    SUCCESS(1),
    FAILURE(2),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return FAILURE;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  private void clearResult() {
    resultCase_ = 0;
    result_ = null;
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  /**
   * <code>.HearRateProto success = 1;</code>
   */
  @java.lang.Override
  public boolean hasSuccess() {
    return resultCase_ == 1;
  }
  /**
   * <code>.HearRateProto success = 1;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.proto.HearRateProto getSuccess() {
    if (resultCase_ == 1) {
       return (com.rookmotion.rook_sdk_health_connect.proto.HearRateProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.proto.HearRateProto.getDefaultInstance();
  }
  /**
   * <code>.HearRateProto success = 1;</code>
   */
  private void setSuccess(com.rookmotion.rook_sdk_health_connect.proto.HearRateProto value) {
    value.getClass();
  result_ = value;
    resultCase_ = 1;
  }
  /**
   * <code>.HearRateProto success = 1;</code>
   */
  private void mergeSuccess(com.rookmotion.rook_sdk_health_connect.proto.HearRateProto value) {
    value.getClass();
  if (resultCase_ == 1 &&
        result_ != com.rookmotion.rook_sdk_health_connect.proto.HearRateProto.getDefaultInstance()) {
      result_ = com.rookmotion.rook_sdk_health_connect.proto.HearRateProto.newBuilder((com.rookmotion.rook_sdk_health_connect.proto.HearRateProto) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 1;
  }
  /**
   * <code>.HearRateProto success = 1;</code>
   */
  private void clearSuccess() {
    if (resultCase_ == 1) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int FAILURE_FIELD_NUMBER = 2;
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   */
  @java.lang.Override
  public boolean hasFailure() {
    return resultCase_ == 2;
  }
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto getFailure() {
    if (resultCase_ == 2) {
       return (com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   */
  private void setFailure(com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto value) {
    value.getClass();
  result_ = value;
    resultCase_ = 2;
  }
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   */
  private void mergeFailure(com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto value) {
    value.getClass();
  if (resultCase_ == 2 &&
        result_ != com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto.getDefaultInstance()) {
      result_ = com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto.newBuilder((com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 2;
  }
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   */
  private void clearFailure() {
    if (resultCase_ == 2) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code HearRateResultProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:HearRateResultProto)
      com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProtoOrBuilder {
    // Construct using com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ResultCase
        getResultCase() {
      return instance.getResultCase();
    }

    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }


    /**
     * <code>.HearRateProto success = 1;</code>
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return instance.hasSuccess();
    }
    /**
     * <code>.HearRateProto success = 1;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.proto.HearRateProto getSuccess() {
      return instance.getSuccess();
    }
    /**
     * <code>.HearRateProto success = 1;</code>
     */
    public Builder setSuccess(com.rookmotion.rook_sdk_health_connect.proto.HearRateProto value) {
      copyOnWrite();
      instance.setSuccess(value);
      return this;
    }
    /**
     * <code>.HearRateProto success = 1;</code>
     */
    public Builder setSuccess(
        com.rookmotion.rook_sdk_health_connect.proto.HearRateProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSuccess(builderForValue.build());
      return this;
    }
    /**
     * <code>.HearRateProto success = 1;</code>
     */
    public Builder mergeSuccess(com.rookmotion.rook_sdk_health_connect.proto.HearRateProto value) {
      copyOnWrite();
      instance.mergeSuccess(value);
      return this;
    }
    /**
     * <code>.HearRateProto success = 1;</code>
     */
    public Builder clearSuccess() {
      copyOnWrite();
      instance.clearSuccess();
      return this;
    }

    /**
     * <code>.SDKExceptionProto failure = 2;</code>
     */
    @java.lang.Override
    public boolean hasFailure() {
      return instance.hasFailure();
    }
    /**
     * <code>.SDKExceptionProto failure = 2;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto getFailure() {
      return instance.getFailure();
    }
    /**
     * <code>.SDKExceptionProto failure = 2;</code>
     */
    public Builder setFailure(com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto value) {
      copyOnWrite();
      instance.setFailure(value);
      return this;
    }
    /**
     * <code>.SDKExceptionProto failure = 2;</code>
     */
    public Builder setFailure(
        com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto.Builder builderForValue) {
      copyOnWrite();
      instance.setFailure(builderForValue.build());
      return this;
    }
    /**
     * <code>.SDKExceptionProto failure = 2;</code>
     */
    public Builder mergeFailure(com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto value) {
      copyOnWrite();
      instance.mergeFailure(value);
      return this;
    }
    /**
     * <code>.SDKExceptionProto failure = 2;</code>
     */
    public Builder clearFailure() {
      copyOnWrite();
      instance.clearFailure();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:HearRateResultProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            "resultCase_",
            com.rookmotion.rook_sdk_health_connect.proto.HearRateProto.class,
            com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002<" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto> parser = PARSER;
        if (parser == null) {
          synchronized (com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:HearRateResultProto)
  private static final com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto DEFAULT_INSTANCE;
  static {
    HearRateResultProto defaultInstance = new HearRateResultProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HearRateResultProto.class, defaultInstance);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.HearRateResultProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HearRateResultProto> PARSER;

  public static com.google.protobuf.Parser<HearRateResultProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

