// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

/**
 * Protobuf type {@code PositionObjectProto}
 */
public  final class PositionObjectProto extends
    com.google.protobuf.GeneratedMessageLite<
        PositionObjectProto, PositionObjectProto.Builder> implements
    // @@protoc_insertion_point(message_implements:PositionObjectProto)
    PositionObjectProtoOrBuilder {
  private PositionObjectProto() {
  }
  public static final int LATDEG_FIELD_NUMBER = 1;
  private double latDeg_;
  /**
   * <code>double latDeg = 1;</code>
   * @return The latDeg.
   */
  @java.lang.Override
  public double getLatDeg() {
    return latDeg_;
  }
  /**
   * <code>double latDeg = 1;</code>
   * @param value The latDeg to set.
   */
  private void setLatDeg(double value) {
    
    latDeg_ = value;
  }
  /**
   * <code>double latDeg = 1;</code>
   */
  private void clearLatDeg() {

    latDeg_ = 0D;
  }

  public static final int LNGDEG_FIELD_NUMBER = 2;
  private double lngDeg_;
  /**
   * <code>double lngDeg = 2;</code>
   * @return The lngDeg.
   */
  @java.lang.Override
  public double getLngDeg() {
    return lngDeg_;
  }
  /**
   * <code>double lngDeg = 2;</code>
   * @param value The lngDeg to set.
   */
  private void setLngDeg(double value) {
    
    lngDeg_ = value;
  }
  /**
   * <code>double lngDeg = 2;</code>
   */
  private void clearLngDeg() {

    lngDeg_ = 0D;
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code PositionObjectProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:PositionObjectProto)
      com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProtoOrBuilder {
    // Construct using com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>double latDeg = 1;</code>
     * @return The latDeg.
     */
    @java.lang.Override
    public double getLatDeg() {
      return instance.getLatDeg();
    }
    /**
     * <code>double latDeg = 1;</code>
     * @param value The latDeg to set.
     * @return This builder for chaining.
     */
    public Builder setLatDeg(double value) {
      copyOnWrite();
      instance.setLatDeg(value);
      return this;
    }
    /**
     * <code>double latDeg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatDeg() {
      copyOnWrite();
      instance.clearLatDeg();
      return this;
    }

    /**
     * <code>double lngDeg = 2;</code>
     * @return The lngDeg.
     */
    @java.lang.Override
    public double getLngDeg() {
      return instance.getLngDeg();
    }
    /**
     * <code>double lngDeg = 2;</code>
     * @param value The lngDeg to set.
     * @return This builder for chaining.
     */
    public Builder setLngDeg(double value) {
      copyOnWrite();
      instance.setLngDeg(value);
      return this;
    }
    /**
     * <code>double lngDeg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLngDeg() {
      copyOnWrite();
      instance.clearLngDeg();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PositionObjectProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "latDeg_",
            "lngDeg_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto> parser = PARSER;
        if (parser == null) {
          synchronized (com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PositionObjectProto)
  private static final com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto DEFAULT_INSTANCE;
  static {
    PositionObjectProto defaultInstance = new PositionObjectProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PositionObjectProto.class, defaultInstance);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.PositionObjectProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PositionObjectProto> PARSER;

  public static com.google.protobuf.Parser<PositionObjectProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

