// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.1

package com.rookmotion.rook_sdk_health_connect.proto;

public final class ProtobufModels {
  private ProtobufModels() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      ProtobufModels.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RookConfigurationProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RookConfigurationProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSourceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DataSourceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSourcesProtoListWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DataSourcesProtoListWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncStatusWithIntProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SyncStatusWithIntProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PluginExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PluginExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultBooleanProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultBooleanProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultInt64Proto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultInt64Proto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultSyncStatusProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultSyncStatusProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultSyncStatusWithIntProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultSyncStatusWithIntProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultDataSourcesProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultDataSourcesProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultRequestPermissionsStatusProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultRequestPermissionsStatusProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014protos.proto\"\211\001\n\026RookConfigurationProt" +
      "o\022\022\n\nclientUUID\030\001 \001(\t\022\021\n\tsecretKey\030\002 \001(\t" +
      "\022*\n\013environment\030\003 \001(\0162\025.RookEnvironmentP" +
      "roto\022\034\n\024enableBackgroundSync\030\004 \001(\010\"\220\001\n\017D" +
      "ataSourceProto\022\014\n\004name\030\001 \001(\t\022\023\n\013descript" +
      "ion\030\002 \001(\t\022\r\n\005image\030\003 \001(\t\022\021\n\tconnected\030\004 " +
      "\001(\010\022\030\n\020authorizationUrl\030\005 \001(\t\022\036\n\026authori" +
      "zationUrlIsNull\030\006 \001(\010\"D\n\033DataSourcesProt" +
      "oListWrapper\022%\n\013dataSources\030\001 \003(\0132\020.Data" +
      "SourceProto\"M\n\026SyncStatusWithIntProto\022$\n" +
      "\nsyncStatus\030\001 \001(\0162\020.SyncStatusProto\022\r\n\005s" +
      "teps\030\002 \001(\r\"A\n\024PluginExceptionProto\022\n\n\002id" +
      "\030\001 \001(\021\022\014\n\004code\030\002 \001(\021\022\017\n\007message\030\003 \001(\t\"h\n" +
      "\022ResultBooleanProto\022\021\n\007success\030\001 \001(\010H\000\0225" +
      "\n\024pluginExceptionProto\030\002 \001(\0132\025.PluginExc" +
      "eptionProtoH\000B\010\n\006result\"d\n\020ResultInt64Pr" +
      "oto\022\017\n\005value\030\001 \001(\003H\000\0225\n\024pluginExceptionP" +
      "roto\030\002 \001(\0132\025.PluginExceptionProtoH\000B\010\n\006r" +
      "esult\"\205\001\n\025ResultSyncStatusProto\022+\n\017syncS" +
      "tatusProto\030\001 \001(\0162\020.SyncStatusProtoH\000\0225\n\024" +
      "pluginExceptionProto\030\002 \001(\0132\025.PluginExcep" +
      "tionProtoH\000B\010\n\006result\"\232\001\n\034ResultSyncStat" +
      "usWithIntProto\0229\n\026syncStatusWithIntProto" +
      "\030\001 \001(\0132\027.SyncStatusWithIntProtoH\000\0225\n\024plu" +
      "ginExceptionProto\030\002 \001(\0132\025.PluginExceptio" +
      "nProtoH\000B\010\n\006result\"\236\001\n\026ResultDataSources" +
      "Proto\022C\n\033dataSourcesProtoListWrapper\030\001 \001" +
      "(\0132\034.DataSourcesProtoListWrapperH\000\0225\n\024pl" +
      "uginExceptionProto\030\002 \001(\0132\025.PluginExcepti" +
      "onProtoH\000B\010\n\006result\"\257\001\n#ResultRequestPer" +
      "missionsStatusProto\022G\n\035requestPermission" +
      "sStatusProto\030\001 \001(\0162\036.RequestPermissionsS" +
      "tatusProtoH\000\0225\n\024pluginExceptionProto\030\002 \001" +
      "(\0132\025.PluginExceptionProtoH\000B\010\n\006result*3\n" +
      "\024RookEnvironmentProto\022\013\n\007SANDBOX\020\000\022\016\n\nPR" +
      "ODUCTION\020\001*N\n\027AvailabilityStatusProto\022\r\n" +
      "\tINSTALLED\020\000\022\021\n\rNOT_INSTALLED\020\001\022\021\n\rNOT_S" +
      "UPPORTED\020\002*4\n\017SyncStatusProto\022\n\n\006SYNCED\020" +
      "\000\022\025\n\021RECORDS_NOT_FOUND\020\001*E\n\024SyncInstruct" +
      "ionProto\022\013\n\007NOTHING\020\000\022\017\n\013SYNC_OLDEST\020\001\022\017" +
      "\n\013SYNC_LATEST\020\002*\377\002\n\023HealthDataTypeProto\022" +
      "\021\n\rSLEEP_SUMMARY\020\000\022\024\n\020PHYSICAL_SUMMARY\020\001" +
      "\022\020\n\014BODY_SUMMARY\020\002\022\022\n\016PHYSICAL_EVENT\020\003\022\034" +
      "\n\030BLOOD_GLUCOSE_BODY_EVENT\020\004\022\035\n\031BLOOD_PR" +
      "ESSURE_BODY_EVENT\020\005\022\026\n\022BODY_METRICS_EVEN" +
      "T\020\006\022\031\n\025HEART_RATE_BODY_EVENT\020\007\022\035\n\031HEART_" +
      "RATE_PHYSICAL_EVENT\020\010\022\030\n\024HYDRATION_BODY_" +
      "EVENT\020\t\022\030\n\024NUTRITION_BODY_EVENT\020\n\022\032\n\026OXY" +
      "GENATION_BODY_EVENT\020\013\022\036\n\032OXYGENATION_PHY" +
      "SICAL_EVENT\020\014\022\032\n\026TEMPERATURE_BODY_EVENT\020" +
      "\r*F\n\035RequestPermissionsStatusProto\022\020\n\014RE" +
      "QUEST_SENT\020\000\022\023\n\017ALREADY_GRANTED\020\001*[\n\023Dat" +
      "aSourceTypeProto\022\n\n\006GARMIN\020\000\022\010\n\004OURA\020\001\022\t" +
      "\n\005POLAR\020\002\022\n\n\006FITBIT\020\003\022\014\n\010WITHINGS\020\004\022\t\n\005W" +
      "HOOP\020\005B@\n,com.rookmotion.rook_sdk_health" +
      "_connect.protoB\016ProtobufModelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RookConfigurationProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RookConfigurationProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RookConfigurationProto_descriptor,
        new java.lang.String[] { "ClientUUID", "SecretKey", "Environment", "EnableBackgroundSync", });
    internal_static_DataSourceProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataSourceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DataSourceProto_descriptor,
        new java.lang.String[] { "Name", "Description", "Image", "Connected", "AuthorizationUrl", "AuthorizationUrlIsNull", });
    internal_static_DataSourcesProtoListWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DataSourcesProtoListWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DataSourcesProtoListWrapper_descriptor,
        new java.lang.String[] { "DataSources", });
    internal_static_SyncStatusWithIntProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SyncStatusWithIntProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SyncStatusWithIntProto_descriptor,
        new java.lang.String[] { "SyncStatus", "Steps", });
    internal_static_PluginExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PluginExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PluginExceptionProto_descriptor,
        new java.lang.String[] { "Id", "Code", "Message", });
    internal_static_ResultBooleanProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ResultBooleanProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResultBooleanProto_descriptor,
        new java.lang.String[] { "Success", "PluginExceptionProto", "Result", });
    internal_static_ResultInt64Proto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ResultInt64Proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResultInt64Proto_descriptor,
        new java.lang.String[] { "Value", "PluginExceptionProto", "Result", });
    internal_static_ResultSyncStatusProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ResultSyncStatusProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResultSyncStatusProto_descriptor,
        new java.lang.String[] { "SyncStatusProto", "PluginExceptionProto", "Result", });
    internal_static_ResultSyncStatusWithIntProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ResultSyncStatusWithIntProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResultSyncStatusWithIntProto_descriptor,
        new java.lang.String[] { "SyncStatusWithIntProto", "PluginExceptionProto", "Result", });
    internal_static_ResultDataSourcesProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ResultDataSourcesProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResultDataSourcesProto_descriptor,
        new java.lang.String[] { "DataSourcesProtoListWrapper", "PluginExceptionProto", "Result", });
    internal_static_ResultRequestPermissionsStatusProto_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ResultRequestPermissionsStatusProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResultRequestPermissionsStatusProto_descriptor,
        new java.lang.String[] { "RequestPermissionsStatusProto", "PluginExceptionProto", "Result", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
