// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface RequestPermissionsStatusResultProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestPermissionsStatusResultProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.RequestPermissionsStatusProto success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.RequestPermissionsStatusProto success = 1;</code>
   * @return The enum numeric value on the wire for success.
   */
  int getSuccessValue();
  /**
   * <code>.RequestPermissionsStatusProto success = 1;</code>
   * @return The success.
   */
  com.rookmotion.rook_sdk_health_connect.proto.RequestPermissionsStatusProto getSuccess();

  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>.SDKExceptionProto failure = 2;</code>
   * @return The failure.
   */
  com.rookmotion.rook_sdk_health_connect.proto.SDKExceptionProto getFailure();

  public com.rookmotion.rook_sdk_health_connect.proto.RequestPermissionsStatusResultProto.ResultCase getResultCase();
}
