// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.0

package com.rookmotion.rook_sdk_health_connect.proto;

public interface ResultRequestPermissionsStatusProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultRequestPermissionsStatusProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return Whether the requestPermissionsStatusProto field is set.
   */
  boolean hasRequestPermissionsStatusProto();
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return The enum numeric value on the wire for requestPermissionsStatusProto.
   */
  int getRequestPermissionsStatusProtoValue();
  /**
   * <code>.RequestPermissionsStatusProto requestPermissionsStatusProto = 1;</code>
   * @return The requestPermissionsStatusProto.
   */
  com.rookmotion.rook_sdk_health_connect.proto.RequestPermissionsStatusProto getRequestPermissionsStatusProto();

  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return Whether the pluginExceptionProto field is set.
   */
  boolean hasPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return The pluginExceptionProto.
   */
  com.rookmotion.rook_sdk_health_connect.proto.PluginExceptionProto getPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  com.rookmotion.rook_sdk_health_connect.proto.PluginExceptionProtoOrBuilder getPluginExceptionProtoOrBuilder();

  com.rookmotion.rook_sdk_health_connect.proto.ResultRequestPermissionsStatusProto.ResultCase getResultCase();
}
