// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.0

package com.rookmotion.rook_sdk_health_connect.proto;

public interface ResultSyncStatusProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultSyncStatusProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SyncStatusProto syncStatusProto = 1;</code>
   * @return Whether the syncStatusProto field is set.
   */
  boolean hasSyncStatusProto();
  /**
   * <code>.SyncStatusProto syncStatusProto = 1;</code>
   * @return The enum numeric value on the wire for syncStatusProto.
   */
  int getSyncStatusProtoValue();
  /**
   * <code>.SyncStatusProto syncStatusProto = 1;</code>
   * @return The syncStatusProto.
   */
  com.rookmotion.rook_sdk_health_connect.proto.SyncStatusProto getSyncStatusProto();

  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return Whether the pluginExceptionProto field is set.
   */
  boolean hasPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   * @return The pluginExceptionProto.
   */
  com.rookmotion.rook_sdk_health_connect.proto.PluginExceptionProto getPluginExceptionProto();
  /**
   * <code>.PluginExceptionProto pluginExceptionProto = 2;</code>
   */
  com.rookmotion.rook_sdk_health_connect.proto.PluginExceptionProtoOrBuilder getPluginExceptionProtoOrBuilder();

  com.rookmotion.rook_sdk_health_connect.proto.ResultSyncStatusProto.ResultCase getResultCase();
}
