// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface SaturationGranularDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaturationGranularDataProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <code>double saturationPercentage = 2;</code>
   * @return The saturationPercentage.
   */
  double getSaturationPercentage();
}
