// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface SpeedGranularDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpeedGranularDataProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <code>sint32 intervalDurationSeconds = 2;</code>
   * @return The intervalDurationSeconds.
   */
  int getIntervalDurationSeconds();

  /**
   * <code>double speedMetersPerSecond = 3;</code>
   * @return The speedMetersPerSecond.
   */
  double getSpeedMetersPerSecond();
}
