// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.1

package com.rookmotion.rook_sdk_health_connect.proto;

public interface SyncStatusWithIntProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SyncStatusWithIntProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SyncStatusProto syncStatus = 1;</code>
   * @return The enum numeric value on the wire for syncStatus.
   */
  int getSyncStatusValue();
  /**
   * <code>.SyncStatusProto syncStatus = 1;</code>
   * @return The syncStatus.
   */
  com.rookmotion.rook_sdk_health_connect.proto.SyncStatusProto getSyncStatus();

  /**
   * <code>uint32 steps = 2;</code>
   * @return The steps.
   */
  int getSteps();
}
