// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

/**
 * Protobuf type {@code TemperatureObjectProto}
 */
public  final class TemperatureObjectProto extends
    com.google.protobuf.GeneratedMessageLite<
        TemperatureObjectProto, TemperatureObjectProto.Builder> implements
    // @@protoc_insertion_point(message_implements:TemperatureObjectProto)
    TemperatureObjectProtoOrBuilder {
  private TemperatureObjectProto() {
    measurementType_ = "";
  }
  public static final int TEMPERATURECELSIUS_FIELD_NUMBER = 1;
  private double temperatureCelsius_;
  /**
   * <code>double temperatureCelsius = 1;</code>
   * @return The temperatureCelsius.
   */
  @java.lang.Override
  public double getTemperatureCelsius() {
    return temperatureCelsius_;
  }
  /**
   * <code>double temperatureCelsius = 1;</code>
   * @param value The temperatureCelsius to set.
   */
  private void setTemperatureCelsius(double value) {
    
    temperatureCelsius_ = value;
  }
  /**
   * <code>double temperatureCelsius = 1;</code>
   */
  private void clearTemperatureCelsius() {

    temperatureCelsius_ = 0D;
  }

  public static final int MEASUREMENTTYPE_FIELD_NUMBER = 2;
  private java.lang.String measurementType_;
  /**
   * <code>string measurementType = 2;</code>
   * @return The measurementType.
   */
  @java.lang.Override
  public java.lang.String getMeasurementType() {
    return measurementType_;
  }
  /**
   * <code>string measurementType = 2;</code>
   * @return The bytes for measurementType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMeasurementTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(measurementType_);
  }
  /**
   * <code>string measurementType = 2;</code>
   * @param value The measurementType to set.
   */
  private void setMeasurementType(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    measurementType_ = value;
  }
  /**
   * <code>string measurementType = 2;</code>
   */
  private void clearMeasurementType() {

    measurementType_ = getDefaultInstance().getMeasurementType();
  }
  /**
   * <code>string measurementType = 2;</code>
   * @param value The bytes for measurementType to set.
   */
  private void setMeasurementTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    measurementType_ = value.toStringUtf8();

  }

  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code TemperatureObjectProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:TemperatureObjectProto)
      com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProtoOrBuilder {
    // Construct using com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>double temperatureCelsius = 1;</code>
     * @return The temperatureCelsius.
     */
    @java.lang.Override
    public double getTemperatureCelsius() {
      return instance.getTemperatureCelsius();
    }
    /**
     * <code>double temperatureCelsius = 1;</code>
     * @param value The temperatureCelsius to set.
     * @return This builder for chaining.
     */
    public Builder setTemperatureCelsius(double value) {
      copyOnWrite();
      instance.setTemperatureCelsius(value);
      return this;
    }
    /**
     * <code>double temperatureCelsius = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperatureCelsius() {
      copyOnWrite();
      instance.clearTemperatureCelsius();
      return this;
    }

    /**
     * <code>string measurementType = 2;</code>
     * @return The measurementType.
     */
    @java.lang.Override
    public java.lang.String getMeasurementType() {
      return instance.getMeasurementType();
    }
    /**
     * <code>string measurementType = 2;</code>
     * @return The bytes for measurementType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMeasurementTypeBytes() {
      return instance.getMeasurementTypeBytes();
    }
    /**
     * <code>string measurementType = 2;</code>
     * @param value The measurementType to set.
     * @return This builder for chaining.
     */
    public Builder setMeasurementType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMeasurementType(value);
      return this;
    }
    /**
     * <code>string measurementType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMeasurementType() {
      copyOnWrite();
      instance.clearMeasurementType();
      return this;
    }
    /**
     * <code>string measurementType = 2;</code>
     * @param value The bytes for measurementType to set.
     * @return This builder for chaining.
     */
    public Builder setMeasurementTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMeasurementTypeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:TemperatureObjectProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "temperatureCelsius_",
            "measurementType_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto> parser = PARSER;
        if (parser == null) {
          synchronized (com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:TemperatureObjectProto)
  private static final com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto DEFAULT_INSTANCE;
  static {
    TemperatureObjectProto defaultInstance = new TemperatureObjectProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TemperatureObjectProto.class, defaultInstance);
  }

  public static com.rookmotion.rook_sdk_health_connect.proto.TemperatureObjectProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TemperatureObjectProto> PARSER;

  public static com.google.protobuf.Parser<TemperatureObjectProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

