// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos.proto
// Protobuf Java Version: 4.28.3

package com.rookmotion.rook_sdk_health_connect.proto;

public interface TemperatureGranularDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TemperatureGranularDataProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <code>double temperatureCelsius = 2;</code>
   * @return The temperatureCelsius.
   */
  double getTemperatureCelsius();

  /**
   * <code>string measurementType = 3;</code>
   * @return The measurementType.
   */
  java.lang.String getMeasurementType();
  /**
   * <code>string measurementType = 3;</code>
   * @return The bytes for measurementType.
   */
  com.google.protobuf.ByteString
      getMeasurementTypeBytes();
}
