// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos.proto

// Protobuf Java Version: 3.25.3
package com.rookmotion.rook_sdk_health_connect.data.proto;

/**
 * Protobuf type {@code ResultDataSourceProto}
 */
public final class ResultDataSourceProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ResultDataSourceProto)
    ResultDataSourceProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResultDataSourceProto.newBuilder() to construct.
  private ResultDataSourceProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResultDataSourceProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResultDataSourceProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rookmotion.rook_sdk_health_connect.data.proto.ProtobufModels.internal_static_ResultDataSourceProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rookmotion.rook_sdk_health_connect.data.proto.ProtobufModels.internal_static_ResultDataSourceProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.class, com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.Builder.class);
  }

  private int resultCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    DATASOURCEPROTOLISTWRAPPER(1),
    SDKNOTINITIALIZEDEXCEPTIONPROTO(8),
    USERNOTINITIALIZEDEXCEPTIONPROTO(10),
    GENERICEXCEPTIONPROTO(11),
    SDKNOTAUTHORIZEDEXCEPTIONPROTO(13),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return DATASOURCEPROTOLISTWRAPPER;
        case 8: return SDKNOTINITIALIZEDEXCEPTIONPROTO;
        case 10: return USERNOTINITIALIZEDEXCEPTIONPROTO;
        case 11: return GENERICEXCEPTIONPROTO;
        case 13: return SDKNOTAUTHORIZEDEXCEPTIONPROTO;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int DATASOURCEPROTOLISTWRAPPER_FIELD_NUMBER = 1;
  /**
   * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
   * @return Whether the dataSourceProtoListWrapper field is set.
   */
  @java.lang.Override
  public boolean hasDataSourceProtoListWrapper() {
    return resultCase_ == 1;
  }
  /**
   * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
   * @return The dataSourceProtoListWrapper.
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper getDataSourceProtoListWrapper() {
    if (resultCase_ == 1) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance();
  }
  /**
   * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapperOrBuilder getDataSourceProtoListWrapperOrBuilder() {
    if (resultCase_ == 1) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance();
  }

  public static final int SDKNOTINITIALIZEDEXCEPTIONPROTO_FIELD_NUMBER = 8;
  /**
   * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
   * @return Whether the sdkNotInitializedExceptionProto field is set.
   */
  @java.lang.Override
  public boolean hasSdkNotInitializedExceptionProto() {
    return resultCase_ == 8;
  }
  /**
   * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
   * @return The sdkNotInitializedExceptionProto.
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto getSdkNotInitializedExceptionProto() {
    if (resultCase_ == 8) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProtoOrBuilder getSdkNotInitializedExceptionProtoOrBuilder() {
    if (resultCase_ == 8) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance();
  }

  public static final int USERNOTINITIALIZEDEXCEPTIONPROTO_FIELD_NUMBER = 10;
  /**
   * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
   * @return Whether the userNotInitializedExceptionProto field is set.
   */
  @java.lang.Override
  public boolean hasUserNotInitializedExceptionProto() {
    return resultCase_ == 10;
  }
  /**
   * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
   * @return The userNotInitializedExceptionProto.
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto getUserNotInitializedExceptionProto() {
    if (resultCase_ == 10) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProtoOrBuilder getUserNotInitializedExceptionProtoOrBuilder() {
    if (resultCase_ == 10) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance();
  }

  public static final int GENERICEXCEPTIONPROTO_FIELD_NUMBER = 11;
  /**
   * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
   * @return Whether the genericExceptionProto field is set.
   */
  @java.lang.Override
  public boolean hasGenericExceptionProto() {
    return resultCase_ == 11;
  }
  /**
   * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
   * @return The genericExceptionProto.
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto getGenericExceptionProto() {
    if (resultCase_ == 11) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProtoOrBuilder getGenericExceptionProtoOrBuilder() {
    if (resultCase_ == 11) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance();
  }

  public static final int SDKNOTAUTHORIZEDEXCEPTIONPROTO_FIELD_NUMBER = 13;
  /**
   * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
   * @return Whether the sdkNotAuthorizedExceptionProto field is set.
   */
  @java.lang.Override
  public boolean hasSdkNotAuthorizedExceptionProto() {
    return resultCase_ == 13;
  }
  /**
   * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
   * @return The sdkNotAuthorizedExceptionProto.
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto getSdkNotAuthorizedExceptionProto() {
    if (resultCase_ == 13) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance();
  }
  /**
   * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
   */
  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProtoOrBuilder getSdkNotAuthorizedExceptionProtoOrBuilder() {
    if (resultCase_ == 13) {
       return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_;
    }
    return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCase_ == 1) {
      output.writeMessage(1, (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_);
    }
    if (resultCase_ == 8) {
      output.writeMessage(8, (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_);
    }
    if (resultCase_ == 10) {
      output.writeMessage(10, (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_);
    }
    if (resultCase_ == 11) {
      output.writeMessage(11, (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_);
    }
    if (resultCase_ == 13) {
      output.writeMessage(13, (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_);
    }
    if (resultCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_);
    }
    if (resultCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_);
    }
    if (resultCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_);
    }
    if (resultCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto)) {
      return super.equals(obj);
    }
    com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto other = (com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto) obj;

    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 1:
        if (!getDataSourceProtoListWrapper()
            .equals(other.getDataSourceProtoListWrapper())) return false;
        break;
      case 8:
        if (!getSdkNotInitializedExceptionProto()
            .equals(other.getSdkNotInitializedExceptionProto())) return false;
        break;
      case 10:
        if (!getUserNotInitializedExceptionProto()
            .equals(other.getUserNotInitializedExceptionProto())) return false;
        break;
      case 11:
        if (!getGenericExceptionProto()
            .equals(other.getGenericExceptionProto())) return false;
        break;
      case 13:
        if (!getSdkNotAuthorizedExceptionProto()
            .equals(other.getSdkNotAuthorizedExceptionProto())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resultCase_) {
      case 1:
        hash = (37 * hash) + DATASOURCEPROTOLISTWRAPPER_FIELD_NUMBER;
        hash = (53 * hash) + getDataSourceProtoListWrapper().hashCode();
        break;
      case 8:
        hash = (37 * hash) + SDKNOTINITIALIZEDEXCEPTIONPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getSdkNotInitializedExceptionProto().hashCode();
        break;
      case 10:
        hash = (37 * hash) + USERNOTINITIALIZEDEXCEPTIONPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getUserNotInitializedExceptionProto().hashCode();
        break;
      case 11:
        hash = (37 * hash) + GENERICEXCEPTIONPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getGenericExceptionProto().hashCode();
        break;
      case 13:
        hash = (37 * hash) + SDKNOTAUTHORIZEDEXCEPTIONPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getSdkNotAuthorizedExceptionProto().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResultDataSourceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResultDataSourceProto)
      com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rookmotion.rook_sdk_health_connect.data.proto.ProtobufModels.internal_static_ResultDataSourceProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rookmotion.rook_sdk_health_connect.data.proto.ProtobufModels.internal_static_ResultDataSourceProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.class, com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.Builder.class);
    }

    // Construct using com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (dataSourceProtoListWrapperBuilder_ != null) {
        dataSourceProtoListWrapperBuilder_.clear();
      }
      if (sdkNotInitializedExceptionProtoBuilder_ != null) {
        sdkNotInitializedExceptionProtoBuilder_.clear();
      }
      if (userNotInitializedExceptionProtoBuilder_ != null) {
        userNotInitializedExceptionProtoBuilder_.clear();
      }
      if (genericExceptionProtoBuilder_ != null) {
        genericExceptionProtoBuilder_.clear();
      }
      if (sdkNotAuthorizedExceptionProtoBuilder_ != null) {
        sdkNotAuthorizedExceptionProtoBuilder_.clear();
      }
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rookmotion.rook_sdk_health_connect.data.proto.ProtobufModels.internal_static_ResultDataSourceProto_descriptor;
    }

    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto getDefaultInstanceForType() {
      return com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto build() {
      com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto buildPartial() {
      com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto result = new com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto result) {
      result.resultCase_ = resultCase_;
      result.result_ = this.result_;
      if (resultCase_ == 1 &&
          dataSourceProtoListWrapperBuilder_ != null) {
        result.result_ = dataSourceProtoListWrapperBuilder_.build();
      }
      if (resultCase_ == 8 &&
          sdkNotInitializedExceptionProtoBuilder_ != null) {
        result.result_ = sdkNotInitializedExceptionProtoBuilder_.build();
      }
      if (resultCase_ == 10 &&
          userNotInitializedExceptionProtoBuilder_ != null) {
        result.result_ = userNotInitializedExceptionProtoBuilder_.build();
      }
      if (resultCase_ == 11 &&
          genericExceptionProtoBuilder_ != null) {
        result.result_ = genericExceptionProtoBuilder_.build();
      }
      if (resultCase_ == 13 &&
          sdkNotAuthorizedExceptionProtoBuilder_ != null) {
        result.result_ = sdkNotAuthorizedExceptionProtoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto) {
        return mergeFrom((com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto other) {
      if (other == com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto.getDefaultInstance()) return this;
      switch (other.getResultCase()) {
        case DATASOURCEPROTOLISTWRAPPER: {
          mergeDataSourceProtoListWrapper(other.getDataSourceProtoListWrapper());
          break;
        }
        case SDKNOTINITIALIZEDEXCEPTIONPROTO: {
          mergeSdkNotInitializedExceptionProto(other.getSdkNotInitializedExceptionProto());
          break;
        }
        case USERNOTINITIALIZEDEXCEPTIONPROTO: {
          mergeUserNotInitializedExceptionProto(other.getUserNotInitializedExceptionProto());
          break;
        }
        case GENERICEXCEPTIONPROTO: {
          mergeGenericExceptionProto(other.getGenericExceptionProto());
          break;
        }
        case SDKNOTAUTHORIZEDEXCEPTIONPROTO: {
          mergeSdkNotAuthorizedExceptionProto(other.getSdkNotAuthorizedExceptionProto());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDataSourceProtoListWrapperFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 1;
              break;
            } // case 10
            case 66: {
              input.readMessage(
                  getSdkNotInitializedExceptionProtoFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 8;
              break;
            } // case 66
            case 82: {
              input.readMessage(
                  getUserNotInitializedExceptionProtoFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 10;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getGenericExceptionProtoFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 11;
              break;
            } // case 90
            case 106: {
              input.readMessage(
                  getSdkNotAuthorizedExceptionProtoFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 13;
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper, com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapperOrBuilder> dataSourceProtoListWrapperBuilder_;
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     * @return Whether the dataSourceProtoListWrapper field is set.
     */
    @java.lang.Override
    public boolean hasDataSourceProtoListWrapper() {
      return resultCase_ == 1;
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     * @return The dataSourceProtoListWrapper.
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper getDataSourceProtoListWrapper() {
      if (dataSourceProtoListWrapperBuilder_ == null) {
        if (resultCase_ == 1) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance();
      } else {
        if (resultCase_ == 1) {
          return dataSourceProtoListWrapperBuilder_.getMessage();
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance();
      }
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    public Builder setDataSourceProtoListWrapper(com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper value) {
      if (dataSourceProtoListWrapperBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        dataSourceProtoListWrapperBuilder_.setMessage(value);
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    public Builder setDataSourceProtoListWrapper(
        com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.Builder builderForValue) {
      if (dataSourceProtoListWrapperBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        dataSourceProtoListWrapperBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    public Builder mergeDataSourceProtoListWrapper(com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper value) {
      if (dataSourceProtoListWrapperBuilder_ == null) {
        if (resultCase_ == 1 &&
            result_ != com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance()) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.newBuilder((com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 1) {
          dataSourceProtoListWrapperBuilder_.mergeFrom(value);
        } else {
          dataSourceProtoListWrapperBuilder_.setMessage(value);
        }
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    public Builder clearDataSourceProtoListWrapper() {
      if (dataSourceProtoListWrapperBuilder_ == null) {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
        }
        dataSourceProtoListWrapperBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    public com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.Builder getDataSourceProtoListWrapperBuilder() {
      return getDataSourceProtoListWrapperFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapperOrBuilder getDataSourceProtoListWrapperOrBuilder() {
      if ((resultCase_ == 1) && (dataSourceProtoListWrapperBuilder_ != null)) {
        return dataSourceProtoListWrapperBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 1) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance();
      }
    }
    /**
     * <code>.DataSourceProtoListWrapper dataSourceProtoListWrapper = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper, com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapperOrBuilder> 
        getDataSourceProtoListWrapperFieldBuilder() {
      if (dataSourceProtoListWrapperBuilder_ == null) {
        if (!(resultCase_ == 1)) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.getDefaultInstance();
        }
        dataSourceProtoListWrapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper, com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapperOrBuilder>(
                (com.rookmotion.rook_sdk_health_connect.data.proto.DataSourceProtoListWrapper) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 1;
      onChanged();
      return dataSourceProtoListWrapperBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProtoOrBuilder> sdkNotInitializedExceptionProtoBuilder_;
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     * @return Whether the sdkNotInitializedExceptionProto field is set.
     */
    @java.lang.Override
    public boolean hasSdkNotInitializedExceptionProto() {
      return resultCase_ == 8;
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     * @return The sdkNotInitializedExceptionProto.
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto getSdkNotInitializedExceptionProto() {
      if (sdkNotInitializedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 8) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance();
      } else {
        if (resultCase_ == 8) {
          return sdkNotInitializedExceptionProtoBuilder_.getMessage();
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    public Builder setSdkNotInitializedExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto value) {
      if (sdkNotInitializedExceptionProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        sdkNotInitializedExceptionProtoBuilder_.setMessage(value);
      }
      resultCase_ = 8;
      return this;
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    public Builder setSdkNotInitializedExceptionProto(
        com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.Builder builderForValue) {
      if (sdkNotInitializedExceptionProtoBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        sdkNotInitializedExceptionProtoBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 8;
      return this;
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    public Builder mergeSdkNotInitializedExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto value) {
      if (sdkNotInitializedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 8 &&
            result_ != com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance()) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.newBuilder((com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 8) {
          sdkNotInitializedExceptionProtoBuilder_.mergeFrom(value);
        } else {
          sdkNotInitializedExceptionProtoBuilder_.setMessage(value);
        }
      }
      resultCase_ = 8;
      return this;
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    public Builder clearSdkNotInitializedExceptionProto() {
      if (sdkNotInitializedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 8) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 8) {
          resultCase_ = 0;
          result_ = null;
        }
        sdkNotInitializedExceptionProtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.Builder getSdkNotInitializedExceptionProtoBuilder() {
      return getSdkNotInitializedExceptionProtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProtoOrBuilder getSdkNotInitializedExceptionProtoOrBuilder() {
      if ((resultCase_ == 8) && (sdkNotInitializedExceptionProtoBuilder_ != null)) {
        return sdkNotInitializedExceptionProtoBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 8) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProtoOrBuilder> 
        getSdkNotInitializedExceptionProtoFieldBuilder() {
      if (sdkNotInitializedExceptionProtoBuilder_ == null) {
        if (!(resultCase_ == 8)) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.getDefaultInstance();
        }
        sdkNotInitializedExceptionProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProtoOrBuilder>(
                (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotInitializedExceptionProto) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 8;
      onChanged();
      return sdkNotInitializedExceptionProtoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProtoOrBuilder> userNotInitializedExceptionProtoBuilder_;
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     * @return Whether the userNotInitializedExceptionProto field is set.
     */
    @java.lang.Override
    public boolean hasUserNotInitializedExceptionProto() {
      return resultCase_ == 10;
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     * @return The userNotInitializedExceptionProto.
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto getUserNotInitializedExceptionProto() {
      if (userNotInitializedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 10) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance();
      } else {
        if (resultCase_ == 10) {
          return userNotInitializedExceptionProtoBuilder_.getMessage();
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    public Builder setUserNotInitializedExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto value) {
      if (userNotInitializedExceptionProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        userNotInitializedExceptionProtoBuilder_.setMessage(value);
      }
      resultCase_ = 10;
      return this;
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    public Builder setUserNotInitializedExceptionProto(
        com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.Builder builderForValue) {
      if (userNotInitializedExceptionProtoBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        userNotInitializedExceptionProtoBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 10;
      return this;
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    public Builder mergeUserNotInitializedExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto value) {
      if (userNotInitializedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 10 &&
            result_ != com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance()) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.newBuilder((com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 10) {
          userNotInitializedExceptionProtoBuilder_.mergeFrom(value);
        } else {
          userNotInitializedExceptionProtoBuilder_.setMessage(value);
        }
      }
      resultCase_ = 10;
      return this;
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    public Builder clearUserNotInitializedExceptionProto() {
      if (userNotInitializedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 10) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 10) {
          resultCase_ = 0;
          result_ = null;
        }
        userNotInitializedExceptionProtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    public com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.Builder getUserNotInitializedExceptionProtoBuilder() {
      return getUserNotInitializedExceptionProtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProtoOrBuilder getUserNotInitializedExceptionProtoOrBuilder() {
      if ((resultCase_ == 10) && (userNotInitializedExceptionProtoBuilder_ != null)) {
        return userNotInitializedExceptionProtoBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 10) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProtoOrBuilder> 
        getUserNotInitializedExceptionProtoFieldBuilder() {
      if (userNotInitializedExceptionProtoBuilder_ == null) {
        if (!(resultCase_ == 10)) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.getDefaultInstance();
        }
        userNotInitializedExceptionProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProtoOrBuilder>(
                (com.rookmotion.rook_sdk_health_connect.data.proto.UserNotInitializedExceptionProto) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 10;
      onChanged();
      return userNotInitializedExceptionProtoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProtoOrBuilder> genericExceptionProtoBuilder_;
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     * @return Whether the genericExceptionProto field is set.
     */
    @java.lang.Override
    public boolean hasGenericExceptionProto() {
      return resultCase_ == 11;
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     * @return The genericExceptionProto.
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto getGenericExceptionProto() {
      if (genericExceptionProtoBuilder_ == null) {
        if (resultCase_ == 11) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance();
      } else {
        if (resultCase_ == 11) {
          return genericExceptionProtoBuilder_.getMessage();
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    public Builder setGenericExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto value) {
      if (genericExceptionProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        genericExceptionProtoBuilder_.setMessage(value);
      }
      resultCase_ = 11;
      return this;
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    public Builder setGenericExceptionProto(
        com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.Builder builderForValue) {
      if (genericExceptionProtoBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        genericExceptionProtoBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 11;
      return this;
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    public Builder mergeGenericExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto value) {
      if (genericExceptionProtoBuilder_ == null) {
        if (resultCase_ == 11 &&
            result_ != com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance()) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.newBuilder((com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 11) {
          genericExceptionProtoBuilder_.mergeFrom(value);
        } else {
          genericExceptionProtoBuilder_.setMessage(value);
        }
      }
      resultCase_ = 11;
      return this;
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    public Builder clearGenericExceptionProto() {
      if (genericExceptionProtoBuilder_ == null) {
        if (resultCase_ == 11) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 11) {
          resultCase_ = 0;
          result_ = null;
        }
        genericExceptionProtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    public com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.Builder getGenericExceptionProtoBuilder() {
      return getGenericExceptionProtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProtoOrBuilder getGenericExceptionProtoOrBuilder() {
      if ((resultCase_ == 11) && (genericExceptionProtoBuilder_ != null)) {
        return genericExceptionProtoBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 11) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProtoOrBuilder> 
        getGenericExceptionProtoFieldBuilder() {
      if (genericExceptionProtoBuilder_ == null) {
        if (!(resultCase_ == 11)) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.getDefaultInstance();
        }
        genericExceptionProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProtoOrBuilder>(
                (com.rookmotion.rook_sdk_health_connect.data.proto.GenericExceptionProto) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 11;
      onChanged();
      return genericExceptionProtoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProtoOrBuilder> sdkNotAuthorizedExceptionProtoBuilder_;
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     * @return Whether the sdkNotAuthorizedExceptionProto field is set.
     */
    @java.lang.Override
    public boolean hasSdkNotAuthorizedExceptionProto() {
      return resultCase_ == 13;
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     * @return The sdkNotAuthorizedExceptionProto.
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto getSdkNotAuthorizedExceptionProto() {
      if (sdkNotAuthorizedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 13) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance();
      } else {
        if (resultCase_ == 13) {
          return sdkNotAuthorizedExceptionProtoBuilder_.getMessage();
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    public Builder setSdkNotAuthorizedExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto value) {
      if (sdkNotAuthorizedExceptionProtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        sdkNotAuthorizedExceptionProtoBuilder_.setMessage(value);
      }
      resultCase_ = 13;
      return this;
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    public Builder setSdkNotAuthorizedExceptionProto(
        com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.Builder builderForValue) {
      if (sdkNotAuthorizedExceptionProtoBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        sdkNotAuthorizedExceptionProtoBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 13;
      return this;
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    public Builder mergeSdkNotAuthorizedExceptionProto(com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto value) {
      if (sdkNotAuthorizedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 13 &&
            result_ != com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance()) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.newBuilder((com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 13) {
          sdkNotAuthorizedExceptionProtoBuilder_.mergeFrom(value);
        } else {
          sdkNotAuthorizedExceptionProtoBuilder_.setMessage(value);
        }
      }
      resultCase_ = 13;
      return this;
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    public Builder clearSdkNotAuthorizedExceptionProto() {
      if (sdkNotAuthorizedExceptionProtoBuilder_ == null) {
        if (resultCase_ == 13) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 13) {
          resultCase_ = 0;
          result_ = null;
        }
        sdkNotAuthorizedExceptionProtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.Builder getSdkNotAuthorizedExceptionProtoBuilder() {
      return getSdkNotAuthorizedExceptionProtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    @java.lang.Override
    public com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProtoOrBuilder getSdkNotAuthorizedExceptionProtoOrBuilder() {
      if ((resultCase_ == 13) && (sdkNotAuthorizedExceptionProtoBuilder_ != null)) {
        return sdkNotAuthorizedExceptionProtoBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 13) {
          return (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_;
        }
        return com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.SDKNotAuthorizedExceptionProto sdkNotAuthorizedExceptionProto = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProtoOrBuilder> 
        getSdkNotAuthorizedExceptionProtoFieldBuilder() {
      if (sdkNotAuthorizedExceptionProtoBuilder_ == null) {
        if (!(resultCase_ == 13)) {
          result_ = com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.getDefaultInstance();
        }
        sdkNotAuthorizedExceptionProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto.Builder, com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProtoOrBuilder>(
                (com.rookmotion.rook_sdk_health_connect.data.proto.SDKNotAuthorizedExceptionProto) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 13;
      onChanged();
      return sdkNotAuthorizedExceptionProtoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ResultDataSourceProto)
  }

  // @@protoc_insertion_point(class_scope:ResultDataSourceProto)
  private static final com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto();
  }

  public static com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultDataSourceProto>
      PARSER = new com.google.protobuf.AbstractParser<ResultDataSourceProto>() {
    @java.lang.Override
    public ResultDataSourceProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResultDataSourceProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultDataSourceProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rookmotion.rook_sdk_health_connect.data.proto.ResultDataSourceProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

